WebOfTrust/keripy

- src/keri/core/eventing.py
- src/keri/core/scheming.py
- src/keri/vc/proving.py
- src/keri/vc/walleting.py
- tests/core/test_scheming.py
- tests/vc/test_handling.py
- tests/vc/test_proving.py
- tests/vc/test_walleting.py
* Changed format of VC to get closer to AC/DC and farther from W3C.
* Fixed bug in Credentialer for SAID generation.
* Fixed Saider to take serialization type into account for SAID generation.
* Added test coverage for Credentialer serialization  formats.
> Changed format of VC plus bug fixes and test coverage

- src/keri/app/cli/commands/incept.py
- src/keri/app/cli/commands/send.py
- src/keri/core/scheming.py
- src/keri/demo/demo_vic.py
- src/keri/demo/demoing.py
- src/keri/vc/handling.py
- src/keri/vc/proving.py
- tests/vc/test_handling.py
- tests/vc/test_proving.py
- tests/vc/test_walleting.py
* Fixed incept and send commands to exit properly by removing all Doers and returning from processing.
* Updated ProofHandler to output presentations on a buffer for consumption downstream.  Updated Vic to process that buffer
* Added vLEI AC/DC credential schema to temporary in memory schema cache.
* Updated Credentialer to return AC/DC complaint credentials by default.
> Fixed incept and send commands to exit properly

- src/keri/app/agenting.py
- src/keri/app/cli/commands/incept.py
- src/keri/app/cli/commands/query.py
- src/keri/app/cli/commands/send.py
- src/keri/app/cli/commands/witness/start.py
- src/keri/app/indirecting.py
- src/keri/app/obtaining.py
- src/keri/demo/demoing.py
- src/keri/peer/httping.py
- src/keri/vdr/verifying.py
- src/keri/vdr/viring.py
- tests/app/cli/gleif-sample.json
- tests/app/cli/wan-witness-sample.json
- tests/app/cli/wes-witness-sample.json
- tests/app/cli/wil-witness-sample.json
- tests/app/test_agenting.py
- tests/app/test_obtaining.py
- tests/conftest.py
- tests/peer/test_exchanging.py
- tests/peer/test_httping.py
* Hardening witnesses to be launched with existing identities
* Fixing incept command line to use salt option
* Added query command line for requesting information from a witness about a KEL
* Tests for peer module.
> Hardening witnesses to be launched with existing identities plus other CLI features

- src/keri/app/cli/commands/query.py
- src/keri/app/habbing.py
- src/keri/app/storing.py
- src/keri/core/__init__.py
- src/keri/core/eventing.py
- src/keri/core/parsing.py
- src/keri/db/basing.py
- src/keri/kering.py
- src/keri/vc/__init__.py
- src/keri/vdr/__init__.py
- src/keri/vdr/eventing.py
- src/keri/vdr/verifying.py
- tests/core/test_eventing.py
- tests/core/test_keystate.py
- tests/db/test_basing.py
* Key state notification as a reply message.
* Added checks for source, accepting ksn only from my watchers, controller of aid or witnesses of aid.
* Removed route (`r`) field from key state notice.
* Docstring updates for `vdr.eventing`
> Key state notification as a reply message.

- src/keri/app/agenting.py
- src/keri/app/cli/commands/vc/issue.py
- src/keri/app/cli/commands/vc/query.py
- src/keri/app/cli/commands/vc/revoke.py
- src/keri/app/habbing.py
- src/keri/app/indirecting.py
- src/keri/core/eventing.py
- src/keri/core/parsing.py
- src/keri/core/routing.py
- src/keri/db/basing.py
- src/keri/db/escrowing.py
- src/keri/kering.py
- src/keri/vdr/eventing.py
- src/keri/vdr/issuing.py
- src/keri/vdr/registering.py
- src/keri/vdr/verifying.py
- src/keri/vdr/viring.py
- tests/app/test_agenting.py
- tests/core/test_keystate.py
- tests/core/test_reply.py
- tests/db/test_escrowing.py
- tests/vdr/test_eventing.py
- tests/vdr/test_issuing.py
- tests/vdr/test_txn_state.py
- tests/vdr/test_verifying.py
Included in this PR: 
* TSN as reply support in Tevery.
* Revery for processing reply messages that uses a Router for routing to other handlers for the specific content of the data block.
* Broker class to maintain escrows and release from escrows when appropriate conditions are met.
* Added kli vc commands for query and revoke credential and fixed the vc issue command.
> TSN as reply support in Tevery.

- src/keri/core/coring.py
- src/keri/core/eventing.py
- tests/core/test_eventing.py
* Fix to prevent incept utility method from creating a non-trans identifier with witnesses or anchors.
* Fix to prevent Kevery from processing non-trans inception event with witnesses or anchors.
Closes #65 
Closes GLEIF-IT/vLEI#74
> Prevent non-transferable identifier icp from having witnesses or anchors

- src/keri/core/eventing.py
- src/keri/vdr/eventing.py
- tests/core/test_kevery.py
Use persisted witness state to determine if receipts should be processed for a given event instead of current witness state of the in memory Kever.  This allows for processing of state events / receipts.
Closes #102
> Use persisted witness state to determine if receipts should be processed

- src/keri/core/coring.py
- src/keri/core/eventing.py
- tests/core/test_bare.py
- tests/core/test_coring.py
bare, bre and prod, prd messages for
Use prod to initiate request for bare response
use bare in unintiated respose
data that is anchored in KEL via a digest seal of some type.
So uses the BADA logic for anchored data.
> removed "expose", exp, message. Replaced now with pair of messages

- src/keri/vdr/eventing.py
> Revocation cues from Tevery in support of the reporting API.

- src/keri/core/coring.py
- src/keri/core/eventing.py
- tests/comply/test_direct_mode.py
- tests/core/test_coring.py
- tests/core/test_eventing.py
- tests/db/test_subing.py
Added checks for non-zeroed pad bits or lead bytes on init of Indexer. 
Added new indexed signature codes to support which list an indexed signature belonds (current or next or both)
> Preparations for Indexer to support new rotation rules

- scripts/demo/credentials/single-issuer.sh
- scripts/demo/data/ecr-auth-data.json
- scripts/demo/data/ecr-auth-edges-filter.jq
- scripts/demo/data/ecr-auth-rules.json
- scripts/demo/data/ecr-edges-filter.jq
- scripts/demo/data/ecr-rules.json
- scripts/demo/data/legal-entity-edges-filter.jq
- scripts/demo/data/oor-auth-data.json
- scripts/demo/data/oor-auth-edges-filter.jq
- scripts/demo/data/oor-edges-filter.jq
- scripts/demo/data/xbrl-edges-filter.jq
- scripts/demo/vLEI/issue-xbrl-attestation-agent.sh
- scripts/demo/vLEI/issue-xbrl-attestation.sh
- scripts/demo/vLEI/qar.sh
- scripts/keri/cf/demo-witness-oobis-schema.json
- scripts/keri/cf/vlei-gar-oobis-schema.json
- scripts/keri/cf/vlei-lar-oobis-schema.json
- scripts/keri/cf/vlei-qar-oobis-schema.json
- scripts/keri/cf/vlei-root-oobis-schema.json
- src/keri/app/cli/commands/vc/issue.py
- src/keri/app/cli/commands/vc/revoke.py
- src/keri/app/indirecting.py
- src/keri/vdr/credentialing.py
- tests/app/test_kiwiing.py
Updating the KLI revoke command to work and added `--send` parameter to specify AIDs or alias of recipients for the events of the revocation.
Updated issue-xbrl-attestation.sh to work with final version of vLEI credential schema.
Updates single-issuer.sh to work with new schema and to include a revocation command.
Added --private flag to the issue command for adding the needed nonces to a credential to enable privacy preserving presentations.
> Final round of changes to support presentation of credentials and revocations.

- scripts/keri/cf/demo-witness-oobis-schema.json
- src/keri/app/cli/commands/kevers.py
- src/keri/app/cli/commands/multisig/incept.py
- src/keri/app/cli/commands/multisig/rotate.py
- src/keri/app/cli/commands/query.py
- src/keri/app/cli/commands/rotate.py
- src/keri/app/delegating.py
- src/keri/app/forwarding.py
- src/keri/app/grouping.py
- src/keri/app/kiwiing.py
- src/keri/db/basing.py
* Add to all delegated commands (kli and agent) a call to send the committed delegated event back to the delegator with all witness receipts at the end of the process.  Also ensure the sending Hab is not a multisig group.
* Fix agent to accept `private` flag for indicating a credential with support for privacy preserving presentation
* Fix agent to allow for empty edges section.
> Delegated event propagation to delegator (and two bug fixes)

- src/keri/app/cli/commands/rotate.py
- src/keri/app/cli/common/rotating.py
- src/keri/app/grouping.py
- src/keri/app/habbing.py
- src/keri/app/keeping.py
- src/keri/app/kiwiing.py
- src/keri/db/basing.py
- src/keri/vdr/credentialing.py
- tests/app/cli/test_kli_commands.py
- tests/app/test_grouping.py
- tests/app/test_keeping.py
- tests/core/test_escrow.py
- tests/core/test_weighted_threshold.py
New rotation rules will require that current signing threshold isith is not the same as the prior next signing threshold 
so rotations must support both independently. The default is for isith to be the prior next when not provided so mostly backwards compatible. The old sith which was the new next threshold is now nsith for next threshold.
> Updated rotation apis and parameters to support both an isith and nsith for current and next thresholds

- src/keri/app/booting.py
> Force booting to create a random salt in the agent if none is specified by the client for creating a data store / key store.

- src/keri/app/agenting.py
- src/keri/app/indirecting.py
Fix for issue #313 
The code was not handling "not urls" case which caused KeyError from following statement. Added raise MissingEntryError. Handling this error in indirecting.py by letting the while loop retry the operation.
agenting.httpClient is invoked from some other places in code. I have not improved error handling in those places.
> Issue 313 crash when witness missing

- src/keri/app/kiwiing.py
Fix for issue #314
I'd like to suggest fixing this by raising HTTPNotFound exception
With this change the error looks like this
```
$  curl -i -s http://localhost:5620/ids/notfound
HTTP/1.1 404 Not Found
Content-Type: application/json
Vary: Accept
Content-Length: 77
Server: Ioflo WSGI Server
Date: Wed, 05 Oct 2022 15:49:19 GMT
{"title": "404 Not Found", "description": "no identifier for alias notfound"}
```
I can also apply this style of fix to other places where http errors are generated.
> Issue 314 invalid content type

- src/keri/app/habbing.py
- src/keri/app/keeping.py
- src/keri/core/eventing.py
- src/keri/db/basing.py
- src/keri/db/dbing.py
- tests/core/test_eventing.py
No code or tests use the new dual index where the current and prior next are different.  but the new logic does not break the old code. Next work is to update the validation logic to use the dual index when used.
> Hab.sign now supports dual index for new rotation rules that is backwards compatible with old.

- src/keri/app/cli/commands/saidify.py
- src/keri/app/oobiing.py
- src/keri/db/basing.py
- tests/app/test_oobiing.py
- tests/db/test_basing.py
Add support for processing a multi OOBI (MOOBI) in the form of a rpy message, processing each URL embedded in the MOOBI and not marking the URL for the MOOBI as resolved until all embedded URLs are complete.
Also enhanced the Oobiery tests by serving real OOBIs (and now MOOBI) from an enpoint and actually resolving them.
> Add support for processing a multi OOBI (MOOBI) in the form of a rpy message

- src/keri/app/cli/kli.py
This MR prevents the exception when calling `kli` without any arguments and prints the help.
The snippet is taken straight from the [project docs](https://pypi.org/project/multicommand/).
**Before:**
```sh
kli
```
**After:**
```sh
kli
```
> fix(kli): Show help when called with no arguments

- src/keri/app/cli/commands/incept.py
- src/keri/app/habbing.py
- src/keri/app/kiwiing.py
Allows inception with data. Tested from `kli incept` and from API `ids/{alias}`.
> Allow data at inception

- src/keri/app/grouping.py
- tests/app/test_grouping.py
Fix Counselor to accept a partial rotation of a group multisig AID when a threshold satisfying number of members have rotated their local AIDs, regardless of the initial list provided.
> Fix Counselor to accept a partial rotation of a group multisig AID correctly.

- src/keri/app/agenting.py
- src/keri/app/cli/commands/mailbox/debug.py
- src/keri/app/cli/commands/mailbox/update.py
- src/keri/app/cli/commands/witness/submit.py
- src/keri/app/cli/kli.py
New utility to look at an AID's mailbox on a given witness
New utility to update current index for an AID's mailbox for a topic on a witness (use with care).
Additional `--force-` option to `kli submit` to force it to send all receipts to all witnesses even if it already has a full compliment.
> 2 new command line tools and one new option

- src/keri/app/cli/commands/interact.py
`kli interact` command did not request a query for receipts when submitting the `ixn` event. The code for receipts were there, but not exactly as in `rotate` and `incept` kli commands. I changed it to mach the code in `rotate.py` and `incept.py` and it's now submitting the `qry` ilk message.
> Fix query for receipts on kli interact 

- src/keri/app/cli/commands/challenge/respond.py
- src/keri/app/cli/commands/delegate/confirm.py
- src/keri/app/cli/commands/delegate/request.py
- src/keri/app/cli/commands/incept.py
- src/keri/app/cli/commands/mailbox/debug.py
- src/keri/app/cli/commands/multisig/continue.py
- src/keri/app/cli/commands/vc/present.py
- src/keri/app/cli/common/displaying.py
- src/keri/app/delegating.py
- src/keri/app/forwarding.py
- src/keri/app/habbing.py
- src/keri/app/indirecting.py
- src/keri/app/kiwiing.py
- src/keri/app/oobiing.py
- src/keri/app/signing.py
- src/keri/vdr/credentialing.py
- tests/app/test_delegating.py
Extract BaseHab and create Hab and GroupHab as instances specific for single and group respectively.
Lays the foundation for an EdgeHab in support of Signify
> Hab class refactor

- scripts/demo/basic/clear.sh
- scripts/demo/data/rotate-sample.json
- src/keri/app/cli/commands/incept.py
- src/keri/app/cli/commands/multisig/interact.py
- src/keri/app/cli/commands/multisig/rotate.py
- src/keri/app/cli/commands/rotate.py
- src/keri/app/cli/common/config.py
- src/keri/app/cli/common/incepting.py
- src/keri/app/cli/common/rotating.py
- src/keri/app/habbing.py
- tests/app/cli/rotate-sample.json
- tests/app/cli/test_kli_commands.py
This adds in the support for using a configuration file (JSON) to configure a rotation event as well as support for using command line arguments to configure an inception event for all relevant configuration properties of each type of event.
The --file argument is no longer required for "incept" nor is it required for "rotate" though there are a minimum set of required attributes checked for "incept" that maps to the existing sample configuration "transferable-sample.json" file.
There are a few code cleanups like the `config.parse_data` for the "data" attribute parsing and the moving of parsing the file options to `config.load_file_options`.
This addresses #274
> Unify CLI args for incept and rotate

- src/keri/app/cli/commands/rollback.py
- src/keri/app/cli/commands/status.py
- src/keri/app/cli/kli.py
This is pop an interaction event off the end of a KEL as long as there are not witness receipts and it is an interaction event.  Use with caution!
> New utility to rollback an interaction event that has not been published to witnesses.

- scripts/demo/test_scripts.sh
- src/keri/app/cli/commands/rotate.py
Also fixes test_scripts.sh to actually fail when one of the sub-scripts is broken by a PR.
> Update rotate command to not barf with no toad is specified.

- Makefile
- README.md
- images/witness.demo.dockerfile
- setup.py
- src/keri/__init__.py
This is the precursor PR for merging development to main.
> Version bump to 1.0 for KERIpy main branch, docker image, PyPi release.

- src/keri/core/coring.py
- tests/core/test_coring.py
- tests/core/test_crypto.py
This PR locks the params we use for stretching keying material using libsodium. This will allow us to have more control over when the algorithm and params are updated, as they will be under ours. If the current Argon2 implementation is found to be flawed, it will likely be removed and the net effect will be the same. This just prevents libsodium from changing their defaults and breaking our implementation.
Locks libsodium pwhash algorithm and params throughout.
Created test vectors for all security tiers and verified they pass using the library constants and also the locked values.
> Lock `libsodium` pwhash algo/params

- src/keri/app/cli/commands/vc/issue.py
Status message for kli vc issue assumed that filename would always be credential.json; this changes it to report (accurately) what the actual output filename will be.
> make status msg accurate

- src/keri/app/cli/commands/local/watch.py
- src/keri/app/cli/commands/multisig/update.py
This was broken with the update to correctly forward all messages from witnesses.
> Update `local watch` and `multisig update` commands to query correctly for the right mailboxes to work with replies

- setup.py
- src/keri/app/cli/commands/ssh/export.py
This PR adds the ssh export command for exporting keys in SSH format to enable easy ssh access through the KASSH server.
> Add ssh export command to the kli

- ref/tel.md
Updates stale documentation. I didn't really see much else that could be improved.
[Pretty version](https://github.com/jasoncolburne/keripy/blob/update-tel-docs/ref/tel.md)
- adds nonce to VC MGMT and TEL fields
- adds `d` throughout with correctly computed saids
- updates `v` strings to use correct lengths
- adds `ri` to `rev` example, as required by the [code](https://github.com/WebOfTrust/keripy/blob/development/src/keri/vdr/eventing.py#L2016-L2017)
- adds `n` to VC TEL example events and `vcp` events
- apply json formatting for examples - not sure how I feel about this, it's easier to read but highlights attachments in red
> Update TEL Documentation

- src/keri/app/agenting.py
- src/keri/app/cli/commands/mailbox/debug.py
- src/keri/app/httping.py
- src/keri/app/indirecting.py
- tests/app/test_httping.py
This PR allows HTTP/CESR requests to work with multi-tenant agents, or any controller infrastructure hosted behind a router.
> Add destination header to HTTP streamed CESR

- src/keri/vdr/verifying.py
- tests/conftest.py
- tests/vdr/test_verifying.py
I think this could could be changed - I seems like it might be unintentional.
When I use this branch I can verify complex ACDC graphs we produce that have attestations in places other than the end of a chain. `development` is breaking my integration tests, and I'm hoping this was just an oversight.
If it makes sense please merge!
> Allow untargeted ACDCs before end of chain

- src/keri/vdr/verifying.py
I thought that `nodeSaid not in [i.qb64 for i in iss]` was actually checking something it wasn't. Turns out the issuer == node issuee check needs to be explicit. I found this when implementing parity in Rust. I noticed our credential graph failed to pass there but was passing here. This should fix things.
> Fix I2I operator

- src/keri/core/coring.py
- src/keri/core/serdering.py
- src/keri/kering.py
- tests/core/test_serdering.py
The core functionality of new Serder is largely complete. 
Most of what remains is fleshing out the .Labels table to include
all the packet types for KERI. ACDC currently only has one default packet type so that is done.
Also still need to add the subclasses with protocol specific and (when necessary) packet type speciific properties.
Also still need to add protocol and packet type specific additional verifications to ._verify augmentation.
Did some refatoring. Moved the versioning stuff from coring to kering  see of better spot.
> Added version support for new Serder. Added prelim surport for both ACDC and KERI protocols

- src/keri/end/ending.py
- src/keri/vdr/credentialing.py
This PR includes a new SignifyRegistry class for creating credential registries (and other credential operations) from a signify Client.
> SignifyRegistry to support signing at the edge for credential functions.

- scripts/demo/credentials/multisig-issuer.sh
- src/keri/app/cli/commands/vc/revoke.py
- src/keri/vdr/eventing.py
This PR adds the date time stamp as an option to `kli revoke` that must be shared between revocation participants.
> Update the kli revoke command to support multisig revocation

- src/keri/app/cli/commands/incept.py
- src/keri/app/cli/commands/rotate.py
- src/keri/app/habbing.py
- src/keri/app/indirecting.py
- src/keri/app/storing.py
This PR includes a bug fix that prevented `kli rotate` from getting receipts from newly added witnesses.  The system was not adding a poller for the new witness so it could not get receipts.  Now it can.
> allow the rotate command to add witness poller for any new witnesses.

- src/keri/core/eventing.py
- src/keri/db/basing.py
This PR removes the key state escrow logic and databases since key state notices are no longer top level KERI events and can not end up in escrow.  The processing was actually disabled a while ago when KSNs were shifted to only being sent embedded in reply messages.
> Removing the un-used and no longer needed key state escrow.

- src/keri/app/cli/commands/delegate/confirm.py
- src/keri/app/cli/commands/delegate/request.py
- src/keri/app/cli/commands/multisig/incept.py
- src/keri/app/cli/commands/multisig/interact.py
- src/keri/app/cli/commands/multisig/notice.py
- src/keri/app/cli/commands/multisig/rotate.py
- src/keri/app/grouping.py
- src/keri/app/habbing.py
- src/keri/app/kiwiing.py
- src/keri/app/oobiing.py
- src/keri/app/signing.py
- src/keri/vdr/credentialing.py
HabitatRecord is not being reliably kept up to date with existing signing and rotation members, so we are changing to a brute force search for existing members of a Group hab via public keys and next key digests.
> Finding group multisig members using keys and the database

- scripts/demo/README.md
Paths in README modified to point to demo/basic/<script-name>.sh from demo/<script-name>.sh which was incorrect according to the current repository.
> Small change to where shell scripts live in demo/README.md

- src/keri/app/cli/commands/agent/vlei.py
- src/keri/app/cli/commands/witness/start.py
KLI --TCP arg had "HTTP" in the help text instead of "TCP".  Quick fix to avoid future confusion if anyone noticed.
> Fixed TCP Arg help text in kli witness

- src/keri/app/habbing.py
- tests/app/cli/test_kli_commands.py
- tests/app/test_habbing.py
In some places, we inline a "default" salt; in others, we use this package-level salt.
Given I think we should discourage the use of any default salt (seems like a bad security practice) I opted to move the creation of the salt to where it is used.
This came up as I was testing Signifypy and mocking the keripy library.
As a note: I have started another branch https://github.com/m00sey/keripy/tree/remove-default-salt to investigate what removing a default salt and requiring one be provided, would look like and the impact on keripy.
> Remove package level salt

- src/keri/app/cli/commands/multisig/join.py
Members can now join if they already have an updated version of the KEL with a valid event that adds them as a member.
> Allow for group member to join group in rotation with valid KEL

- src/keri/app/cli/commands/witness/start.py
- src/keri/app/indirecting.py
- tests/app/test_indirecting.py
Adds the same args from `kli agent start` to `kli witness start`.
If the base function `createHttpServer` is accepted into KERIpy then we can change my PR to KERIA to use that function rather than duplicate it.
This is missing a positive test for creating a `tcp.ServerTls` instance. I just need to figure out how to generate self-signed TLS certs on the fly or add a test set of TLS certs+key to the test fixtures.
> Add witness TLS support

- scripts/demo/credentials/multisig-issuer-interactive.sh
- scripts/demo/credentials/multisig-issuer.sh
- src/keri/app/agenting.py
- src/keri/app/cli/commands/escrow.py
- src/keri/app/cli/commands/ipex/admit.py
- src/keri/app/cli/commands/ipex/grant.py
- src/keri/app/cli/commands/ipex/list.py
- src/keri/app/cli/commands/multisig/join.py
- src/keri/app/cli/commands/multisig/rotate.py
- src/keri/app/cli/commands/passcode/remove.py
- src/keri/app/cli/commands/passcode/set.py
- src/keri/app/cli/commands/vc/create.py
- src/keri/app/cli/commands/vc/list.py
- src/keri/app/cli/commands/vc/registry/incept.py
- src/keri/app/cli/commands/vc/registry/list.py
- src/keri/app/cli/commands/vc/revoke.py
- src/keri/app/grouping.py
- src/keri/app/habbing.py
- src/keri/app/indirecting.py
- src/keri/core/eventing.py
- src/keri/core/parsing.py
- src/keri/peer/exchanging.py
- src/keri/vc/protocoling.py
- src/keri/vdr/credentialing.py
- src/keri/vdr/eventing.py
- src/keri/vdr/verifying.py
- tests/app/test_grouping.py
- tests/vc/test_protocoling.py
* Multisig credental creation
* Multisig IPEX grant and admit message support
* Script (mutlisig-issuance.sh) exercising the functionality of multisig credential issuance with IPEX grant and admit messages having both participants agree out of band all all steps in the process (thus never executing the join command).
* Script (mutlisig-issuance-intractive.sh) exercising the functionality of multisig credential issuance with IPEX grant and admit messages having one participant lead each step and the second participant executing the join command.
> Interactive and non-Interactive multisig credential issuance with IPEX grant and admit

- src/keri/db/dbing.py
- tests/db/test_dbing.py
_Note: I wish there was something a little more elegant to this fix, but it seemed better to keep the lmdb exceptions close to the classes and methods rather than trying something more fancy or a key_validation() type function to signal intent_
LMBD throws lmdb.BadValSizeError which isn't very helpful (or caught) in the codebase although KeyErrors are because of the dict abstraction elsewhere.  (Found while trying to resolve Issue #575)
So now the LMDB methods throw KeyError where appropriate and tests for all methods with empty keys now execute regardless of whether those methods had the issue or not.
> LMDBer methods throw KeyError on malformed keys.

- src/keri/app/cli/common/incepting.py
TOAD is threshold of accountable duplicity, not threshold of acceptable duplicity.
> Correct the KLI description for TOAD

- Contributing.md
- Contributors.md
Rough draft of potential CONTRIBUTORS.md file for discussion/review.
> Feature contributors file

- images/keripy.dockerfile
This is a slight elaboration on Jason's initial work.
Moving the COPY src/ src/ from the build stage to the runtime stage enables near instantaneous builds for source-only updates. 
The `RUN mkdir /keripy/src` in the build layer enables the setup.py and requirements.txt to be able to fully execute.
Building from scratch, or with no cache, a `linux/amd64` image on my Mac takes about 25 minutes. This Dockerfile enables me to have a build that is less than 5 seconds when there are source only changes. However, dependency changes still require a full rebuild.
> Multistage dockerfile example

- src/keri/app/configing.py
This PR includes a minor bug fix to use the `filed` parameter.  Originally submitted by @tibor19
> Use filed parameter in configing.py instead of defaulting to True.

- src/keri/app/indirecting.py
Fix for https://github.com/WebOfTrust/keripy/issues/455
See https://github.com/WebOfTrust/keripy/issues/455#issuecomment-1790912272
Steps to reproduce
```
cd ~/keripy
kli witness demo &
kli witness demo
kill %%
```
With this fix the second kli witness command will fail with non-zero exit status and output
```
ERR: cannot create http server on port 5642
```
> Improving startup error message when binding on tcp port fails

- src/keri/app/habbing.py
This PR is a small fix to Habery.deleteHab to make it actually work.
> Fix delete hab to use the right name.

- src/keri/core/coring.py
- tests/core/test_coring.py
A cipher of a sniffiable stream plaintext may have in its plaintext a CESR stream with  interleaved stream json, cbor, mgpk or groups of qb2 and or qb64. Sniffable means to use the sniff function to look at first tritet to determine serialization format.
Whereas a ciphertext of plaintext that is  qb64 and qb2 is not sniffed.
> Added more ciphertext variable sized codes so now have sniffable stream, qb64, and qb2

- src/keri/app/challenging.py
- tests/app/test_challenging.py
This PR fixes challenge response after being broken by the CESR updates.  Also added tests since this lost coverage when KIWI was deleted.
> Fix reference to .saider in challenge response and add test

- scripts/demo/test_scripts.sh
- src/keri/app/agenting.py
- src/keri/app/habbing.py
- src/keri/app/querying.py
- src/keri/core/eventing.py
- src/keri/vdr/credentialing.py
- src/keri/vdr/eventing.py
- tests/app/test_querying.py
- tests/core/test_escrow.py
- tests/vdr/test_eventing.py
This PR updates all uses of sequence number to ensure we are explicit about passing around hex string for Seals and all parameters unless a mathematical comparison operation is required, then use an int and declare that in doc strings
> Explicit use of hex str or int sequence numbers

- src/keri/app/habbing.py
- src/keri/core/eventing.py
- src/keri/db/basing.py
- src/keri/db/subing.py
- src/keri/kering.py
- tests/core/test_delegating.py
- tests/core/test_escrow.py
- tests/core/test_eventing.py
- tests/core/test_parsing.py
New local logic with event processing and misfit escrowing
But of unit tests now failing but reasons seem consistent with new logic
> habery .__init__ creates its default .psr parser with local = True

- src/keri/core/serdering.py
- src/keri/peer/exchanging.py
- src/keri/vdr/credentialing.py
This PR includes a small bug fix to sendArtifact introduced with the change to new Serder classes.
> Fix sendArtifacts method to use the correct Serder subclass for TEL events.

- src/keri/app/querying.py
- src/keri/core/eventing.py
- src/keri/peer/exchanging.py
This PR fixes last few references to sequence number to use hex string in queries.
> Update query cues to use hex string instead of int for sequence number.

- src/keri/vdr/eventing.py
- src/keri/vdr/viring.py
- tests/vdr/test_txn_state.py
This test fixes a bug introduced when we changed state notices from events to Komer records.  I added a test for Tever.reload so it is now covered.   Fixes issue #667
> Fix Tever.reload to work with RegStateRecord and add unit test

- src/keri/vdr/eventing.py
I was getting an error when reloading a registry after a cold-start KERIA as the following error message shows. Removing `ba` and `br` from the `vdr.eventing.state` function resolved things for me.
```python
2024-02-03 12:27:01 [FALCON] [ERROR] GET /identifiers/{my_aid}/registries => Traceback (most recent call last):
File "falcon/app.py", line 365, in falcon.app.App.__call__
File "/path/to/keria/src/keria/app/credentialing.py", line 92, in on_get
state=asdict(registry.tever.state())
^^^^^^^^^^^^^^^^^^^^^^
File "/path/to/keripy/src/keri/vdr/eventing.py", line 800, in state
br = self.cuts
^^^^^^^^^
AttributeError: 'Tever' object has no attribute 'cuts'
```
> Remove unused ba and br in RegStateRecord state fn

- scripts/demo/basic/challenge.sh
- scripts/demo/credentials/multisig-issuer.sh
- src/keri/app/cli/commands/ipex/grant.py
- src/keri/app/cli/commands/ipex/list.py
- src/keri/app/cli/commands/multisig/join.py
- src/keri/app/cli/commands/vc/create.py
- src/keri/app/cli/commands/vc/export.py
- src/keri/app/querying.py
- src/keri/core/parsing.py
- tests/app/test_querying.py
This PR fixes broken kli commands from the serdering changes and get scripts in scripts/demo/credentials and scripts/demo/vLEI working again.
This closes #666 #665 and #664
> Fix all broken kli commands and sample scripts

- images/keripy.dockerfile
By using a less specific base image we can be right more often while doing less maintenance grunt-work on our Docker image. By using 3.10 instead of 3.10.13, our code will still be correct when 3.10.14 is released. Similarly, by using "alpine" instead of "alpine 3.18", we are still presently using the latest stable version of Alpine 3 (3.18) while being upgraded automatically to the latest stable version when it becomes available.
Reference:
- https://hub.docker.com/layers/library/python/3.10-alpine/images/sha256-4b062a3861ac865436439499d9a03e055871a0f465833987d23b67364a35a38f?context=repo
- https://github.com/docker-library/python/blob/b34fc81375758e84dec797e9210a079b4889352e/3.10/alpine3.18/Dockerfile#L24
Also, fix docker build bug with COPY:
> Step 9/17 : COPY requirements.txt setup.py …
> Use image python:3.10-alpine; Fix docker COPY build failure

- images/keripy.dockerfile
Reverts WebOfTrust/keripy#671
I didn't mean to merge this into development.
> Revert "Use image python:3.10-alpine; Fix docker COPY build failure"

- images/keripy.dockerfile
- src/keri/app/cli/commands/ipex/grant.py
This PR fixes the kli grant command by removing the last reference to `creder.subject`, changing it to the new `creder.attrib`
> One more reference to the deprecated `subject` field in SerderACDC.

- setup.py
- src/keri/core/coring.py
- src/keri/help/helping.py
- tests/core/test_coring.py
Now supports thresholds where each top level weight in a clause can be a weighted set of weights. This effectively adds
another layer of weights.  
```json
[
[
{"1/3": ["1/2", "1/2", "1/2"]}, 
"1/2", 
{"1/2": ["1", "1"]}
],
[
"1/2", 
''{"1/2": ["1", "1"]}
]
]
```
Two ANDed clauses at top level. First top level clause has two weights that are each an block whose label is a weight and whose value is is list of weights. The label is the weight on the set of weights. The other top level weight in the clause is a simple weight.  The second top level cause as one simple weight and one weight that is a block whose label is a weight and whose value is a list of weights.
> Support for nested fractional weight sets as value of top level weight

- scripts/demo/basic/delegate.sh
- scripts/demo/test_scripts.sh
- src/keri/app/cli/commands/delegate/confirm.py
- src/keri/app/cli/commands/rotate.py
- src/keri/app/cli/commands/witness/start.py
- src/keri/app/delegating.py
- Update to `delegate confirm` and `rotate` kli commands to fix delegation approval of rotation from command line.
- Pull in changes from PR #688 that add log level as a command line argument for `witness start` kli command.
> This hotfix adds fixes for rotation from kli and witness arg for logging

- scripts/demo/basic/multisig-quartet.sh
- scripts/demo/data/multisig-quartet-sample.json
- src/keri/app/cli/commands/multisig/rotate.py
- Add the replay topic to multisig rotate kli command mailbox director to receive the response to the query for delegator's anchoring event.
- Updated multisig-quartet script to include delegation and test rotation.
> Fix delegated multisig rotation from KLI

- .gitignore
- src/keri/app/cli/commands/witness/start.py
- src/keri/app/habbing.py
- tests/app/test_delegating.py
- tests/app/test_grouping.py
- tests/app/test_habbing.py
- tests/app/test_httping.py
- tests/app/test_indirecting.py
- tests/app/test_oobiing.py
- tests/core/test_eventing.py
- tests/core/test_kevery.py
- tests/core/test_keystate.py
- tests/core/test_parsing_pathed.py
- tests/core/test_replay.py
- tests/core/test_witness.py
- tests/db/test_basing.py
- tests/demo/test_demo.py
- tests/end/test_ending.py
- tests/peer/test_exchanging.py
- tests/vc/test_protocoling.py
- tests/vdr/test_txn_state.py
- tests/vdr/test_verifying.py
Removed hardcoded salts as default behavior of openHby and openHab.
Also fixed a bug that hadn't been caught yet wherein whatever was passed to openHby was always used and a default salt was never created. Adjusted to match the intention of the code and no tests seemed to break from it so it must have been getting caught further down the stack.
> Non deterministic prefixes in witnesses

- src/keri/vdr/verifying.py
This allows saving most compact variants of ACDCs. I haven't thoroughly tested it but the change seems safe to me, hopefully existing coverage will tell me if I'm wrong.
```
keri: Parser msg non-extraction error: string indices must be integers, not 'str'
Traceback (most recent call last):
File "/Users/jason/github.com/WebOfTrust/keripy/src/keri/core/parsing.py", line 420, in allParsator
done = yield from self.msgParsator(ims=ims,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/jason/github.com/WebOfTrust/keripy/src/keri/core/parsing.py", line 1115, in msgParsator
vry.processCredential(creder=serder, prefixer=prefixer, seqner=seqner, saider=saider)
File "/Users/jason/github.com/WebOfTrust/keripy/src/keri/vdr/verifying.py", line 180, in processCredential
self.saveCredential(creder, …
```
> ensure creder.attrib is not a string before treating it like a dict

- src/keri/app/agenting.py
This PR is a fix for **KERIA** issue [#214](https://github.com/WebOfTrust/keria/issues/214) where a `socket.getaddrinfo` exception is raised in certain conditions causing the witness http client creation to fail.
> Catching socket exception when creating witness http client

- src/keri/app/cli/commands/witness/start.py
As keripy is mostly running inside a docker container, so writing logs into the console makes sense, and we can utilize the docker daemons log rotation feature. Recently we saw keripy also writing logs into a temporary file (in `/tmp` directory) inside the container. And it doesn't rotate the log. So the storage is getting full. And there is no way to modify this behavior without changing the code. I hope this CLI argument will make life easier.
> Writing logs into file is configurable from cli argument

- images/keripy.dockerfile
Not sure how we test docker images but these build and seem to be the latest alpine images that matched the original image.  The witness demo uses the GLEIF images so wasn't sure where to update those.
> Updated docker images to use python 3.12

- src/keri/app/cli/commands/migrate.py
- update migrate command to process only saved credentials
- while migrating keys, skip missing events
> Process only saved credentials during migration

- src/keri/core/eventing.py
This is the same as closed (but not merged)  PR #738.
We are fixing a problem that happens when escrowing replay messages that authorize the EndRole of a multisig, where the EndRole got accepted but the same replay message keeps being escrowed and rejected because the date timestamp is not increasing. Since the authorization event is the same, we are validating that the compared messages are idempotent.
> Fix failing EndRole escrow

- src/keri/app/agenting.py
- src/keri/app/cli/commands/interact.py
- src/keri/app/cli/commands/rotate.py
- src/keri/app/cli/commands/witness/start.py
- src/keri/app/cli/commands/witness/submit.py
- src/keri/app/delegating.py
- src/keri/app/grouping.py
- src/keri/app/habbing.py
- src/keri/app/indirecting.py
- src/keri/core/eventing.py
- src/keri/core/parsing.py
- src/keri/core/routing.py
- src/keri/db/escrowing.py
- src/keri/peer/exchanging.py
- src/keri/vdr/credentialing.py
- src/keri/vdr/eventing.py
- src/keri/vdr/verifying.py
- Removed logging at any level but debug for messages in the escrow loops.
- Removed line feeds from all log levels but debug
- Ensured stack traces are only logged in debug
- Removed full event logging from info, moved to debug level.  Replaced with SAID in info.
- Replaced print statements in grouping and delegating with logger.info statements.
> Logging updates

- src/keri/help/helping.py
Use a raw byte string for the regex so that \Z is properly interpreted as an anchor representing the end of the input, not an escape sequence for the character \Z (which doesn't exist). The hyphen was already moved to the end of the character class so we don't need to worry about escaping that.
> 690 Fix SyntaxWarning: invalid escape sequence

- .github/workflows/python-app-ci.yml
- src/keri/db/basing.py
- src/keri/end/ending.py
- tests/end/test_ending.py
This PR includes a fix to OOBI resolution to account for knowing about a delegated AID without having the delegation approval.  Added test.
Closes #762
> Fix OOBI resolution

- src/keri/app/cli/commands/watcher/__init__.py
- src/keri/app/cli/commands/watcher/add.py
- src/keri/app/cli/commands/witness/authenticate.py
- src/keri/app/habbing.py
- src/keri/app/indirecting.py
- src/keri/app/oobiing.py
- src/keri/core/__init__.py
- src/keri/core/eventing.py
- src/keri/core/parsing.py
- src/keri/db/basing.py
- src/keri/db/escrowing.py
- src/keri/end/ending.py
- tests/app/test_indirecting.py
- tests/app/test_oobiing.py
- tests/end/test_ending.py
* A handler tied into the Oobiery for processing `rpy` messages with a `/introduce` route.  The handler passes the provided OOBI to the Oobiery for resolution.
* The addition of host parameter for creating an HTTP server so it can be created on different network interfaces.
> New introduce rpy handler and updates to create HTTP server

- scripts/demo/basic/multisig-rotation-in-third.sh
- scripts/demo/test_scripts.sh
- src/keri/app/cli/commands/multisig/join.py
- src/keri/app/grouping.py
- src/keri/core/eventing.py
A few fixes to Kever signature verification to re-enable multisig rotation.
* Add check for whether to skip witness threshold checking for locallyMembered.
* Fix method for getting list of local signature indices from a list of multiple signatures to use hab record.
* Re-enable multisig join script in CI.
> Fix multisig rotation

- scripts/demo/basic/multisig-rotate-three-stooges.sh
- scripts/demo/basic/script-utils.sh
- scripts/demo/data/multisig-three-aids.json
This script executes a multisig inception with three AIDs (the stooges), rotates each individual participant's key, shares the latest key state with all participants with `kli query`, and then performs a multisig rotation and interaction.
> test: three stooges multisig rotate and interact

- src/keri/core/__init__.py
- src/keri/core/signing.py
- tests/core/test_eventing.py
- tests/core/test_signing.py
> Remove generateSigners function and refactor with Salter().signers()

- src/keri/app/cli/commands/multisig/rotate.py
This allows use outside of the command line to pass in an existing Habery and avoid passing bran as an argument.
No usages of GroupMultisigRotate in KERIA
No usages of GroupMultisigRotate in Signifypy
Tests pass.
Ran mulltisig-join.sh
> removes bran from GroupMultisigRotate constructor inplace of an existing Habery

- src/keri/app/cli/commands/multisig/join.py
This adds the capability to specify an alias during multisig join. Previously the alias was always set to "test alias" which would cause alias collision problems when doing successive multisig join commands for different identifiers.
> feat: multisig join --group arg

- src/keri/app/cli/commands/delegate/confirm.py
- src/keri/core/eventing.py
- tests/core/test_delegating.py
This PR adds new method Kevery.processEscrowDelegables for attempting to re-process events that require delegation.  This closes #785
> Add processing method for delegables escrow in Kevery

- src/keri/core/eventing.py
- tests/core/test_delegating.py
Adds a message to the MissingDelegableApprovalError so the logging doesn't fail.
Updated test to exercise the exception and logging.
> fixes MissingDelegableApprovalError logging bug

- src/keri/app/storing.py
Should resolve https://github.com/WebOfTrust/keria/issues/184.
In KERIA, the Respondant processes certain cues for a kevery, but it drops other cues like `keyStateSaved` and Phil has suggested this to be the safest change to make to resolve the issue.
Since we are pushing the cue back onto the Deck, I needed to process one item per tock instead of looping the entire Deck and then yielding. An alternative is to keep another list of items and re-add them all after `while self.cues` is finished but I find this risky in case there are a lot of items and the process dies half way through.
> fix: re-cue unmatched cues in Respondant

- src/keri/app/cli/commands/multisig/join.py
I missed this when I changed `--alias` to `--group` a few weeks ago.
> fix: correct short arg for --group from -a to -g

- scripts/demo/basic/multisig-for-revoke-auth.sh
- scripts/demo/data/multisig-sign-auth.json
- src/keri/app/habbing.py
This PR adds a new script modeling revokable authorization with a distributed multisig, as well as a related multisig config file. Additionally, it re-orders GroupHab.make such that HabitatRecord is created, saved, and prefixes are added before event processing begins, accounting for scenarios similar to multisig-for-revoke-auth.sh.
> Add new script for revokable authorization

- src/keri/app/grouping.py
Needed for testing with KERIA, specifically the SIGNIFY-TS multisig-vlei-issuance test
> fix grouping multisig parser to process events in local mode

- src/keri/app/agenting.py
- src/keri/app/cli/commands/delegate/confirm.py
- src/keri/app/cli/commands/local/watch.py
- src/keri/app/cli/commands/mailbox/debug.py
- src/keri/app/cli/commands/mailbox/list.py
- src/keri/app/cli/commands/rotate.py
- src/keri/app/cli/commands/watcher/add.py
- src/keri/app/cli/commands/watcher/adjudicate.py
- src/keri/app/cli/commands/watcher/list.py
- src/keri/app/cli/commands/witness/list.py
- src/keri/app/delegating.py
- src/keri/app/querying.py
- src/keri/app/watching.py
- src/keri/core/eventing.py
- src/keri/core/routing.py
- src/keri/db/basing.py
- tests/app/test_storing.py
- tests/app/test_watching.py
- tests/core/test_reply.py
* New kli commands for listing witnesss, watchers and mailboxes.
* Update to kli command `kli watcher add` to use new BADA-RUN protected data structures for tracking AIDs being observed by a watcher on behalf of a controller
* New kli command to perform key event adjudication across the set of watchers watching an AID.  This command will retrieve updated key state if a threshold satisfying number watchers response with non-duplicitous key state change.
* Addition to rotate and delegate confirm to all the specification of witness auth code time stamps.
* Update to delegation processing to propagate the delegator anchor event to witnesses after delegation approval
* New databases to track observed AIDs (observed by watchers) and delegation propogation escrow.
* Bug fix in …
> New and updated kli commands for witnesss, watchers and mailboxes.  Delegation fixes

- src/keri/app/cli/commands/watcher/add.py
- src/keri/app/indirecting.py
- src/keri/app/watching.py
- src/keri/core/parsing.py
- src/keri/vdr/credentialing.py
- tests/app/test_watching.py
* Fixes to `watcher add` command to allow for multiple aliases that start with the same name.
* Added a feature to turn witnesses search off for MailboxDirector.
> Fixes to `watcher add` command

- src/keri/app/habbing.py
This addresses https://github.com/WebOfTrust/keria/issues/257. There was just a `smids` arg missed in Habery.loadHabs for `SignifyGroupHab`s.
> fix: add smids group hab call

- src/keri/db/basing.py
- src/keri/db/dbing.py
This PR exposes the KERI_BASER_MAP_SIZE environment variable to allow setting the maximum file size for the main KERIpy LMDB database.  By default it is set to 100MB, but LMDB documentation suggests on 64-bit systems it is safe to set it as high as a terabyte or more as long as you have the disk space to handle.
You can also change this value and relaunch any process using KERIpy and it will take effect.
> Externalize the size limit for LMDB map size for Baser to an environment variable.

- src/keri/db/basing.py
- tests/db/test_basing.py
Added log message and exception check for when KERI_BASER_MAP_SIZE not an integer.
Fixes #811
> Fixed KERI_BASER_MAP_SIZE not integer bug.

- setup.py
- src/keri/app/cli/commands/location/add.py
* Update to latest Hio release
* New command line command for adding location records for an AID
> Update to latest Hio build and new kli command

- src/keri/app/cli/commands/introduce.py
- src/keri/app/cli/commands/watcher/adjudicate.py
- src/keri/app/forwarding.py
- src/keri/app/oobiing.py
- src/keri/app/watching.py
- src/keri/core/eventing.py
- src/keri/core/parsing.py
- src/keri/core/routing.py
- A new kli command to send an `/introduce` message with an AID and OOBI.
- Bug fix to watching to check against the correct key state.
- Logging additions, fixes and typo fixes.
> New kli command for introductions and a few fixes

- src/keri/vdr/viring.py
- tests/vdr/test_verifying.py
Fetching a missing credential through KERIA gives a 500 - see description of https://github.com/WebOfTrust/keria/pull/282
This small PR be a cleaner solution that the current PR as we can just catch `kering.MissingEntryError`.
Note - the 500 error comes from the `cancs.get` line but looking at the existing code for saving credentials, it should exist in `cancs` if it's in `creds`.
> feat: raise MissingEntryError for missing credential

- src/keri/app/notifying.py
- src/keri/app/signaling.py
- tests/app/test_notifying.py
- tests/app/test_signaling.py
Notes that are not initiated with a `dt` parameter, are being created with a default `dt` that don't follows the ISO 8601 format. The class use the function `datetime.datetime.now().isoformat()` to create the string timestamp that result in a value without timezone or offset such as `2023-10-05T14:48:23.123456`.
Instead, `keripy` normal use `helping.nowIso8601()` to create the timestamp that result in values like `2021-06-27T21:26:21.233257+00:00`
> Fix notes datetime ISO 8601 format

- scripts/demo/basic/delegate.sh
- src/keri/core/eventing.py
- src/keri/db/basing.py
- Update clone delegation to not raise an exception if the delegator's KEL is not in local kevers
- Fix event handling to walk the KEL to find an anchoring event if it exists.
These changes close #842 by allowing for a witness to return a KEL for a delegated AID without the AES couple for approved events and without the delegator's KEL.
This is the expected behavior for a witness as it should not be assumed that a witness perform watcher functionality.  Any validator will have to be introduced to the delegator or OOBI with the delegator before validating the KEL of the delegate.
> 2 fixes for delegation:

- src/keri/app/agenting.py
- src/keri/app/querying.py
- src/keri/app/watching.py
- src/keri/core/eventing.py
- tests/app/test_querying.py
- tests/core/test_replay.py
This PR allows the specification of `fn` for first seen ordinal as the first event to start streaming back.  This is an optimization to allow witnesses and watchers to only stream the events needed and not the entire KEL every time a new event occurs.
> Update sequence number querying for logs

- src/keri/app/cli/commands/event.py
- src/keri/app/cli/commands/incept.py
- src/keri/app/cli/commands/interact.py
- src/keri/app/cli/commands/multisig/incept.py
- src/keri/app/cli/commands/multisig/rotate.py
- src/keri/app/cli/commands/rotate.py
- src/keri/app/delegating.py
- src/keri/app/forwarding.py
- src/keri/db/basing.py
- src/keri/peer/exchanging.py
- tests/peer/test_exchanging.py
* Updating delegation logic to allow for multiple delegation inception commands to run simultaneously.  
* Ensure proper use of the proxy for delegation inception and rotation kli commands.
* Add timeout to exn escrow for partial sig escrow of peer-to-peer messages.
The first 2 are in support of creating many delegates at once and anchoring them all in the same delegator event.
> Fixes for anchoring multiple delegates in a single delegator event, exn escrow timeout.

- src/keri/core/parsing.py
This change processes ESSR packets with Matter and variable length Bytes code, not Texter.
> Minor update to parsing ESSR attachments.

- src/keri/vdr/viring.py
- tests/vdr/test_verifying.py
PR https://github.com/WebOfTrust/keripy/pull/682 omitted specifying `sn` in the call to `cloneTvtAt` at line 405. This is important for revoked credentials.
See diff changes on line 405 of PR https://github.com/WebOfTrust/keripy/pull/682
This PR inserts again the `sn` parameter.
Additionally, I corrected the sn used to search in the Tel, sn=0 for `iss` or sn=1 for `rev`
> Missing sn in CloneCred after fix in PR #682

- src/keri/app/cli/commands/multisig/join.py
- src/keri/app/cli/commands/multisig/rotate.py
- src/keri/app/habbing.py
- tests/app/test_grouping.py
This updates the database HabitatRecord smids and rmids properties when a group rotation happens.
Fixes https://github.com/WebOfTrust/keripy/issues/856
> fix: update smids and rmids on rotate

- README.md
Installing and configuring Libsodium can be a challenge. This docs update helps Mac users installing it for the first time.
> docs: show libsodium install instructions

- src/keri/app/cli/commands/multisig/rotate.py
- src/keri/app/habbing.py
- tests/app/test_grouping.py
The prior code would fix smids and rmids for all new rotation members on each rotation yet would not fix the smids and rmids for the group lead submitting the multisig event because of the early return when the serder arg is not present. 
This fixes that.
Fixes: https://github.com/WebOfTrust/keripy/issues/856
> fix: update smids and rmids for group lead on new event

- src/keri/app/cli/commands/oobi/resolve.py
- src/keri/app/cli/commands/witness/authenticate.py
- src/keri/end/ending.py
- OOBI resolve now waits until the AID is in Kevers before completing
- Witness authenticate includes the CESR http header.
> Two command line changes:

- scripts/demo/basic/challenge.sh
- src/keri/app/cli/commands/did/generate.py
- src/keri/app/cli/commands/ipex/grant.py
- src/keri/app/cli/commands/oobi/generate.py
- src/keri/app/delegating.py
- src/keri/app/grouping.py
- src/keri/app/oobiing.py
- src/keri/app/querying.py
- src/keri/core/eventing.py
- src/keri/db/basing.py
This fix includes:
* Change `local=local` in calls to `escrowOOEvent` to propagate the locality of the event across out of order escrowing.
* Fix OOBI generation to favor HTTPS over HTTP and to honor the full URL of the service endpoint.
* Use the "Last" variant of the method for finding event seals in all locations.
> Fix calls to out of order escrow

- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/keri_app.rst
- docs/keri_core.rst
- docs/keri_db.rst
- docs/keri_demo.rst
- docs/keri_help.rst
- docs/keri_peer.rst
- docs/keri_vc.rst
- docs/naming.md
- docs/requirements.txt
Upgrade Sphinx to 8.1.3 and myst-parser to 4.1.3.
1. doing `make clean html` builds the docs.
2. Open the docs on OSx with `open _build/html/index.html`
3. Profit
There are a bunch of warnings yet they don't stop the docs from building.
> docs: fix Sphinx build

- docs/keri_db.rst
- src/keri/db/dbing.py
- tests/db/test_dbing.py
We hit the default size set in LMDBer of 104 megabytes and need to set a higher default. This PR sets the default to 4GB and allows setting the size with the `KERI_LMDB_MAP_SIZE` environment variable.
> feat: KERI_LMDB_MAP_SIZE for setting LMDB file size

- src/keri/app/cli/commands/migrate/list.py
- src/keri/app/cli/commands/migrate/run.py
- src/keri/db/basing.py
- src/keri/db/migrations/add_key_and_reg_state_schemas.py
- src/keri/db/migrations/hab_data_rename.py
- src/keri/db/migrations/rekey_habs.py
Add database migrations for:
- `0.6.7` (Jun 16, 2022) -> `0.6.8` (Nov 2, 2022): `hab_data_rename` (new)
- `0.6.8` (Nov 2, 2022) -> `1.0.0` (Mar 31, 2023): `add_key_and_reg_state_schemas` (new)
- `1.0.0` (Mar 31, 2023) -> `1.2.0` (Oct 4, 2024): `rekey_habs` (already existed)
I discovered the need for the `hab_data_rename` migration while testing migration for 0.6.7 test Root GAR databases similar to production as we believe v0.6.7 is what is in production for Root GARs.
The `add_key_and_reg_state_schemas` we initially thought was specific to Provenant yet in my testing it turns out it is needed to take a Root GAR 0.6.7 database up to 1.0.0, so not specific to Provenant.
The `rekey_habs` migration was relabeled from a `1.1.0` migration to be a `1.2.0` migration since it is not applicable to …
> feat: migrates from 0.6.7 to 1.2.0

- scripts/demo/basic/challenge.sh
- scripts/demo/credentials/multisig-grant-multisig-admit.sh
- scripts/demo/credentials/multisig-issuer-interactive.sh
- src/keri/app/cli/commands/contacts/list.py
- src/keri/app/cli/commands/contacts/replace.py
- src/keri/app/oobiing.py
This will resolve WebOfTrust/keria#291 and also avoid the lack of clarity raised in WebOfTrust/keria#292. As dicussed on [Discord](https://discord.com/channels/1148629222647148624/1154416772401860648/1295408495801401396).
kli command added to add the alias using `org.replace`. I added it to the demo scripts that seemed to need the contact to be in place. Many don't require it, but I hope I didn't miss too many.
> feat: de-couple contact creation from OOBI resolution

- src/keri/vdr/credentialing.py
- Fix exception in `sendArtifacts` by adding a null check for issuee in case of presenting untargeted credential
> add null check for issuee in sendArtifacts for presenting untargeted credential.

- src/keri/app/agenting.py
- src/keri/app/cli/commands/interact.py
- src/keri/app/cli/commands/rotate.py
- src/keri/app/cli/commands/witness/authenticate.py
- src/keri/core/eventing.py
This PR includes the following:
* Fix delegation "catchup" logic for witnesses during delegated rotation.
* Fix witness authenticate to handle service endpoint urls with a trailing slash.
* Minor fix to parsing for local delegators and 3 typo fixes
> Last bit of clean up for V1.2.0 rc4

- Makefile
- README.md
- setup.py
- src/keri/__init__.py
- src/keri/app/cli/commands/escrow/clear.py
- src/keri/app/cli/commands/escrow/list.py
- src/keri/app/cli/commands/migrate/run.py
- src/keri/app/cli/kli.py
- src/keri/db/basing.py
- src/keri/db/dbing.py
- src/keri/vdr/viring.py
- tests/app/cli/test_kli_commands.py
This backports `kli escrow clear` and `kli escrow list` into the 1.1.x release branch.
I also added clearing for every escrow I could find as there seemed to be some missing from the 1.2.x branch. I upgraded the `kli escrow list` command to show a count of all existing escrows.
> Clear both KEL and TEL escrows; list all events in escrow, or their counts

- src/keri/core/coring.py
- tests/core/test_coring.py
An Ed448 signature is 114 bytes (binary). When serialized as CESR, there's a 4/3 increase in size, and a prefix. The correct size of this primitive in CESR is 156 bytes, which is what the spec claims, not 56 bytes as currently shown in the Matter class in keripy. (https://asecuritysite.com/signatures/x448_sig)
Fix requested by @SmithSamuelM 
Fixes #892
> fix issue 892

- src/keri/db/basing.py
- src/keri/db/subing.py
- src/keri/help/__init__.py
- tests/db/test_subing.py
Allows us to replace all uses of DeWitness Couple, DeReceiptCouple etc with Suber Instance that handles multiple field Base64 values. This is more effecient and now patterns like other Suber.
> Added B64IoDupSuber and B64OnIoDubSuber classes with unit tests

- src/keri/app/cli/commands/vc/create.py
- src/keri/vc/proving.py
- src/keri/vdr/credentialing.py
- tests/vc/test_proving.py
This adds the privacy preserving nonces that for whatever reason did not come in through https://github.com/WebOfTrust/keripy/pull/901.
> fix: add nonces in prep for private creds

- src/keri/core/eventing.py
- src/keri/core/parsing.py
- src/keri/core/routing.py
- src/keri/db/escrowing.py
- src/keri/help/__init__.py
- src/keri/peer/exchanging.py
- src/keri/vdr/eventing.py
- src/keri/vdr/verifying.py
Description:
- Adds TRACE logging level in `keri.help.__init__` module.
- Moves escrow logs to TRACE logging level.
- Moves event body logging to DEBUG level.
- INFO log level contains SAID or prefix of events rather than an event body.
- Uniformly uses log substitution where it would improve performance.
- Uniformly uses f-strings where performance is equivalent yet readability is enhanced.
- `serder.pretty()` used in favor of `serder.ked` or `json.dumps(serder.ked, indent=1)`
- Added escrow-specific strings to each escrow to clarify in logs which escrow produced which log message.
- Various spelling corrections and wording cleanups like `Kevery process` to `Kevery`
There will be a separate PR to `main` for similar changes. Phil has already made similar changes in `main`.
> refactor: move escrow logs to TRACE and msg body logs to DEBUG

- src/keri/app/cli/commands/vc/create.py
has the fix as mentioned [here](https://github.com/WebOfTrust/keripy/pull/902).
This changes the `store_true` in the two new command line arguments 
`--private-credential-nonce`
and
`--private-subject-nonce`
to have their "action" prop set to store so that they can accept string values rather than be set only to True or False based on presence or absence of the command line arguments like `--private`.
> fix: use store instead of store_true for args expecting nonces

- src/keri/app/indirecting.py
- tests/app/test_indirecting.py
- added /query endpoint in witness agent to query for TEL or KEL events using HTTP GET request
- Closes #672
> feat: add endpoint in witness to query tel event of an aid

- scripts/demo/basic/challenge.sh
- scripts/demo/credentials/multisig-grant-multisig-admit.sh
- scripts/demo/credentials/multisig-issuer-interactive.sh
- setup.py
- src/keri/__init__.py
- src/keri/app/cli/commands/witness/demo.py
- src/keri/app/oobiing.py
- src/keri/peer/exchanging.py
This PR fixes #922 by reintroducing contact creation since it is optional.  It also includes a few minor logging fixes.
> Fix OOBI contact generation

- src/keri/core/eventing.py
This PR allows for delegator and delegate to be in the same Habery.
> Small fix to allow delegate and delegator to be in same Habery.

- src/keri/vdr/credentialing.py
Looks like I missed one detail while pulling in the private credential work from the 1.1.26 branch, the `private=private` argument to `proving.credential()` call, which was failing schema validations on all private credentials. This fixes that.
> fix: add missing private arg to proving.credential()

- src/keri/db/basing.py
- src/keri/db/subing.py
- tests/db/test_basing.py
During a recent issue we had a old "un-parsable" event stuck in escrow.
The current (1.1.31 and 1.2.4) code includes a "count".
The count was only used in a log message, but utilized "getItemIter" which attempts to serialize the message into a serder. Which then throws an exception because it does not have enough required fields.
The `cntAll` is naive as it doesn't account for dupes etc - but it servers the purpose for a count at the most basic level.
> adds a naive count all to SuberBase

- src/keri/app/oobiing.py
On re-resolving of an OOBI then contact data is being erased due to usage of the `Organizer.replace()` function. This is resolved by using `Organizer.update()` which does a merge (in Python, shown below) of data with any existing data.
```python
class Organizer:
...
def update(...):
...
existing = self.get(pre)
if existing is None:
existing = dict()
existing |= data
raw = json.dumps(existing).encode("utf-8")
cigar = self.hby.signator.sign(ser=raw)
self.hby.db.ccigs.pin(keys=(pre,), val=cigar)
self.hby.db.cons.pin(keys=(pre,), val=raw)
field, val in data.items():
self.hby.db.cfld.pin(keys=(pre, field), val=val)
````
> fix: merge instead of replace contact data on re-OOBI

- src/keri/core/routing.py
The logging changes I made earlier this year caused the reply message escrow to no longer work because of a faulty log substitution in `Revery.acceptReply` . This PR fixes that in the `1.2.4` branch, similar to https://github.com/WebOfTrust/keripy/pull/958 for `main`.
I double checked `1.1.32` and found that it does not need this same fix because the logging statement in `Revery.acceptReply` is not present.
> fix logging substitution error

- scripts/demo/basic/challenge.sh
- src/keri/app/cli/commands/challenge/respond.py
- src/keri/app/cli/commands/challenge/verify.py
I found that the `--alias` argument of `kli challenge verify` is not being used for anything.
When you have a keystore with multiple AIDs, the `kli challenge verify` will interactively prompt you for an alias. That threw me off because I could not understand why it would need the alias. So I removed that code and marked the `--alias` argument as "Unused" in the documentation. Hopefully this helps the next person who encounters this. 
The reason I did not remove it completely is to not break backwards compatibility for anyone who is currently passing `--alias` anyway. Perhaps there could be a way to mark deprecated arguments. Please advise.
> remove unused `--alias` argument for `kli challenge verify`

- src/keri/core/eventing.py
Spurious sigs could cause verify to not verify when otherwise could have.
> Fixed bug in verifySigs

- src/keri/core/coring.py
- src/keri/core/counting.py
- src/keri/core/mapping.py
- src/keri/core/parsing.py
- src/keri/core/serdering.py
- src/keri/help/__init__.py
- src/keri/help/helping.py
- tests/core/test_coring.py
- tests/core/test_counting.py
- tests/core/test_mapping.py
- tests/core/test_parsing.py
- tests/help/test_helping.py
… ACDC, SPAC, and TSP_ incase some time infuture
they need to not share the KERI CESR code table.
> Change GenusCodex to reserve the four relevant protocols so have the flexibility to go to a one-to-one instead of shared relationship

- src/keri/core/__init__.py
- src/keri/core/coring.py
- src/keri/core/mapping.py
- tests/core/test_coring.py
- tests/core/test_mapping.py
…g that is verbatim the qb64 of a special type value
such as None, bool, int, float, string or escape. This required adding an special primitive code for Escape So matter serilizer will escape any string field values with new escape code, include the escape code itself.
> Fixed Mapper to round trip correctly even when field value is a string that is verbatim a special value qb64

- src/keri/core/parsing.py
- src/keri/help/helping.py
- src/keri/peer/exchanging.py
Update import of ABCMeta so it works with Python 3.12.6
Set "done" in groupParsator to fix bug when exiting.
> Update exchanging code to use rparts for attachment paths.

- scripts/demo/basic/delegate.sh
- scripts/demo/basic/multisig-delegator.sh
- scripts/demo/basic/script-utils.sh
- scripts/demo/test_scripts.sh
~~The `dip` event never ended up in the delegables escrow. See change in eventing.py.~~
Same fix was merged in #997.
This PR now only adds a test script for multisig delegator to single sig delegatee using _separate_ witnesses for delegator and delegatee.
See also #992, I use the same utility functions and approach to test script here. I can change the other scripts to be implemented this way as well. I can also just put these scripts in a separate repository. Let me know.
> add test script for multisig delegator to single sig delegatee

- scripts/demo/basic/delegate.sh
- scripts/demo/basic/script-utils.sh
This illustrates the issue encountered in #975 and adds the steps needed to resolve it.
I have added some utility functions to make it easier to create isolated keystores and avoid creating config files for each AID. Please advice if you like this approach.
Closes #975
> refactor delegate script to use separate witnesses

- setup.py
- src/keri/app/agenting.py
- src/keri/app/apping.py
- src/keri/app/cli/commands/incept.py
- src/keri/app/cli/commands/init.py
- src/keri/app/cli/commands/multisig/incept.py
- src/keri/app/cli/commands/rotate.py
- src/keri/app/configing.py
- src/keri/app/delegating.py
- src/keri/app/forwarding.py
- src/keri/app/grouping.py
- src/keri/app/habbing.py
- src/keri/app/httping.py
- src/keri/app/indirecting.py
- src/keri/app/keeping.py
- src/keri/app/oobiing.py
- src/keri/app/signaling.py
- src/keri/app/storing.py
- src/keri/db/basing.py
- src/keri/vc/walleting.py
- src/keri/vdr/credentialing.py
- tests/app/test_agenting.py
ported from Sam's commit to main in PR #945Ported from Sam's commit to main in PR #945.
These changes are required in order to upgrade to HIO 0.6.18 or higher. Without these, or similar changes, then some KLI commands break.
Third time's a charm.
> Update Doer method signatures to support new Hio multiprocessing safety

- src/keri/peer/exchanging.py
- src/keri/vdr/credentialing.py
* Bug fix for exchanger, to make sure that ESSR attachments survive an escrowed event.
* Bug fix to ensure one exchanger does not poach another exchanger's escrowed events.
* Fix registry inception to match hio changes.
* Removing log messages that are in the direct line of fire of escrow processing
> A few bug fixes for exchange events

- src/keri/core/eventing.py
- src/keri/core/parsing.py
Move all receipt processing into one Kevery function that contains the logic for what attachments to process.  Removes that logic from the Parser.
> Combining receipt processing functions into one processReceipt function.

- src/keri/core/eventing.py
- src/keri/core/parsing.py
This PR combines receipt process into one function that contains the logic for what attachments to process.  Removes that logic from the Parser.
> Combining receipt processing functions into one function.
