docs/Peer2PeerCredentials.md
src/keri/app/habbing.py
src/keri/core/coring.py
src/keri/core/eventing.py
src/keri/core/parsing.py
src/keri/kering.py
src/keri/peer/exchanging.py
src/keri/vdr/eventing.py
tests/core/test_coring.py
tests/peer/test_exchanging.py

* Added peer.exchanging module for processing new `exn` messages for peer to peer message exchange.
* Added Signer Seal (-S) a couple of (pre+ControllerIndexSigs) for verification of `req` and `exn` messages against the existing signing keys of a controller.

Added peer.exchanging module for processing new `exn` messages for peer to peer message exchange.

---

docs/Peer2PeerCredentials.md
setup.py
src/keri/core/scheming.py
tests/core/test_scheming.py

This PR contains:
* Schemar class for serializing and verifying schema of type JSON Schema (for now) with self-addressing identifiers.
* Generic Sadder class for verifying self-addressing identifiers of JSON documents.

Schemer and Saider for working with self-addressing schema.

---

docs/Peer2PeerCredentials.md
src/keri/app/habbing.py
src/keri/core/coring.py
src/keri/core/scheming.py
src/keri/vc/proving.py
tests/core/test_coring.py
tests/vc/test_proving.py

Credential and Credentialer classes for generating and signing VCs in CESR Proof format

Credential and Credentialer classes for Verifiable Credentials

---

src/keri/core/scheming.py
tests/core/test_scheming.py
tests/vc/test_proving.py

Sample of jsonschema reference resolution that verifies self-addressing identifiers of the schema.

Sample of jsonschema reference resolution

---

src/keri/app/directing.py
src/keri/app/habbing.py
src/keri/app/indirecting.py
src/keri/core/eventing.py
src/keri/core/parsing.py
src/keri/demo/demo_han.py
src/keri/demo/demo_ian.py
src/keri/demo/demo_vic.py
src/keri/demo/demoing.py
src/keri/peer/exchanging.py
src/keri/vc/handling.py
src/keri/vc/proving.py
src/keri/vc/walleting.py
src/keri/vdr/verifying.py
tests/demo/test_demo.py
tests/peer/test_exchanging.py
tests/vc/test_handling.py
tests/vc/test_proving.py
tests/vc/test_walleting.py
tests/vdr/test_issuing.py
tests/vdr/test_viring.py

* Peer to peer handlers for issue credential
* Peer to peer handlers for request presentation and present proof.

Peer to peer protocol handlers for the issue step in the credential issuance flow and request and proof for the proof presentation flow.

---

docs/Peer2PeerCredentials.md
src/keri/demo/demoing.py
src/keri/kli/commands/agent.py
src/keri/peer/exchanging.py
src/keri/peer/httping.py
src/keri/vc/handling.py
tests/peer/test_exchanging.py
tests/vc/test_handling.py

* Skeleton agent controller with HTTP/TCP listeners
* HTTP server for exn messages
* HTTP server  and for req, kel/tel related messages

Skeleton agent controller with HTTP/TCP listeners

---

.github/workflows/interop/Dockerfile
Makefile
docs/getting_started.md
interop/README.md
setup.py

Signed-off-by: Kevin Griffin <griffin.kev@gmail.com>

removing old references

---

src/keri/vc/proving.py
tests/vc/test_handling.py
tests/vc/test_proving.py
tests/vc/test_walleting.py

* Update credential to better support AC/DC credentials with data block containing SAID.

Update credential to better support AC/DC credentials with data block containing SAID.

---

src/keri/app/agenting.py
src/keri/app/cli/commands/agent/start.py
src/keri/app/cli/commands/incept.py
src/keri/app/cli/commands/multisig/incept.py
src/keri/app/cli/commands/rotate.py
src/keri/app/cli/commands/status.py
src/keri/app/directing.py
src/keri/app/habbing.py
src/keri/app/indirecting.py
src/keri/db/basing.py
src/keri/peer/exchanging.py
src/keri/peer/httping.py
tests/app/cli/commands/multisig/multisig-1-sample.json
tests/app/cli/commands/multisig/multisig-2-sample.json
tests/app/cli/commands/multisig/multisig-3-sample.json
tests/app/cli/commands/multisig/multisig-sample.json
tests/app/cli/commands/multisig/test_multisig.py
tests/app/test_agenting.py
tests/db/test_basing.py
tests/demo/test_demo.py
tests/peer/test_mailboxing.py

* Command line command for incepting a multi-sig identifier with keys that originate from distributed key stores.
* Command line for key rotation.  Supports new key and witness configurations.
* HTTP Mailbox for peer to peer communication with a Respondant that routes replies to either local mailbox or witness mailbox depending on the recipient (witnesses or not).

Command line command for incepting a multi-sig identifier

---

.gitignore
Dockerfile
publish.sh
setup.py
src/keri/__init__.py
src/keri/app/agenting.py
src/keri/app/cli/commands/agent/start.py
src/keri/app/cli/commands/incept.py
src/keri/app/cli/commands/multisig/incept.py
src/keri/app/cli/commands/query.py
src/keri/app/cli/commands/rotate.py
src/keri/app/cli/commands/status.py
src/keri/app/cli/commands/wallet/start.py
src/keri/app/indirecting.py
src/keri/app/obtaining.py
src/keri/core/parsing.py
src/keri/demo/demo_han.py
src/keri/end/ending.py
src/keri/peer/exchanging.py
src/keri/peer/httping.py
src/keri/vc/handling.py
src/keri/vc/proving.py
src/keri/vc/walleting.py
src/keri/vdr/issuing.py
tests/app/cli/commands/multisig/multisig-final.json
tests/app/cli/commands/multisig/multisig-sample.json
tests/app/cli/commands/multisig/test_multisig.py
tests/app/cli/holder-sample.json
tests/app/cli/witness-sample.json
tests/peer/test_mailboxing.py

Integration with prototype UI.
Getting rotate commandline to work
Adding Pipfile to gitignore because pipenv keeps creating one and I don't want to check it in.
Adding POST support to mailbox
update mailbox to get
Wallet component for receiving and presenting credentials.  In promiscuous mode for now (will accept and credential and present any requested credential to anyone).
Signed-off-by: Kevin Griffin <griffin.kev@gmail.com>

Bump to verion 0.5.4 after demo.

---

src/keri/app/apping.py
src/keri/app/cli/commands/incept.py
src/keri/app/cli/commands/multisig/incept.py
src/keri/app/cli/commands/query.py
src/keri/app/cli/commands/rotate.py
src/keri/app/indirecting.py
src/keri/vc/proving.py
tests/app/cli/commands/multisig/multisig-1-sample.json
tests/app/cli/commands/multisig/multisig-2-sample.json
tests/app/cli/commands/multisig/multisig-3-sample.json
tests/app/cli/commands/multisig/test_multisig.py
tests/app/cli/ctrl-sample.json
tests/app/cli/gleif-sample.json
tests/app/cli/holder-sample.json
tests/app/cli/wan-witness-sample.json
tests/app/cli/wes-witness-sample.json
tests/app/cli/wil-witness-sample.json
tests/app/cli/witness-sample.json

Fix query, multisig and mailbox to work with new doified methods.

Fixes to commands for new hio.

---

src/keri/core/eventing.py

fixed merge issue with delegation

---

tests/app/test_watching.py

add doist fix of phils to test. fix bad merge

---

scripts/demo/start-agent.sh
src/keri/app/agenting.py
src/keri/app/cli/commands/agent/start.py
src/keri/app/cli/commands/delegate/incept.py
src/keri/app/cli/commands/delegate/rotate.py
src/keri/app/cli/commands/query.py
src/keri/app/cli/commands/rotate.py
src/keri/app/cli/commands/vc/issue.py
src/keri/app/cli/commands/vc/registry/incept.py
src/keri/app/cli/commands/witness/demo.py
src/keri/app/delegating.py
src/keri/app/habbing.py
src/keri/app/indirecting.py
src/keri/app/obtaining.py
src/keri/core/eventing.py
src/keri/db/basing.py
src/keri/vdr/eventing.py
src/keri/vdr/registering.py
tests/app/cli/commands/delegate/incept-sample.json
tests/app/test_delegating.py
tests/app/test_habbing.py

Delegation with could agent at delegator and command line delegatee inception.

Delegation

---

scripts/demo/start-han.sh
src/keri/app/agenting.py
src/keri/app/cli/commands/multisig/interact.py
src/keri/app/cli/commands/wallet/start.py
src/keri/app/grouping.py
src/keri/core/scheming.py
src/keri/demo/demoing.py
src/keri/kering.py
src/keri/vc/handling.py
src/keri/vc/proving.py
src/keri/vc/walleting.py
src/keri/vdr/eventing.py
src/keri/vdr/issuing.py
src/keri/vdr/verifying.py
src/keri/vdr/viring.py
tests/app/test_agent_kiwiserver.py
tests/core/test_scheming.py
tests/vc/test_handling.py
tests/vc/test_proving.py
tests/vc/test_walleting.py
tests/vdr/test_eventing.py
tests/vdr/test_issuing.py
tests/vdr/test_verifying.py

* Integrating verify loop into enterprise wallet.
* Process and verify chains in credentials.
* Remove reliance on JSONSchema from Credentialer.  Moving to credential verification.
* Credential schema validation now integrated into credential verification.

Credential hardening.

---

tests/app/test_delegating.py

Signed-off-by: Kevin Griffin <griffin.kev@gmail.com>

adds delegation test

---

src/keri/app/delegating.py
tests/app/test_delegating.py

Signed-off-by: Kevin Griffin <griffin.kev@gmail.com>

propagating name

---

scripts/demo/multi-delegate.sh
scripts/demo/multi-single.sh
scripts/demo/start-agent.sh
src/keri/app/agenting.py
src/keri/app/cli/commands/agent/start.py
src/keri/app/cli/commands/multisig/incept.py
src/keri/app/cli/commands/query.py
src/keri/app/cli/commands/vc/registry/demo.py
src/keri/app/cli/commands/vc/registry/incept.py
src/keri/app/cli/commands/witness/demo.py
src/keri/app/grouping.py
src/keri/app/indirecting.py
src/keri/core/eventing.py
src/keri/vc/handling.py
src/keri/vc/proving.py
src/keri/vc/walleting.py
src/keri/vdr/eventing.py
src/keri/vdr/issuing.py
src/keri/vdr/registering.py
src/keri/vdr/verifying.py
tests/app/cli/commands/multisig/multisig-delegated-sample.json
tests/app/test_agent_kiwiserver.py
tests/app/test_delegating.py
tests/vc/test_handling.py
tests/vc/test_proving.py
tests/vc/test_walleting.py
tests/vdr/test_issuing.py
tests/vdr/test_verifying.py

Distributed multsig deletated identifier inception from the command line.
Registry creation and credential issuance from multisig delegated identifier.
Updates to registry and credentials after field normalization
Added Group Polling for participants in a multisig group to poll group identifier mailbox

Multisig with delegation

---

src/keri/app/agenting.py
tests/app/test_agenting.py

Deduping calls to witness inquisitor to prevent DDoSing our own witnesses and watchers.

Deduping calls to witness inquisitor

---

scripts/demo/multi-delegate.sh
scripts/demo/start-agent.sh
scripts/pilot/data-user-incept.json
scripts/pilot/gleif-incept.json
scripts/pilot/qvi-incept.json
scripts/pilot/qvi-request.json
scripts/pilot/start-data-user.sh
scripts/pilot/start-gleif.sh
scripts/pilot/start-qvi.sh
src/keri/app/agenting.py
src/keri/app/cli/commands/agent/start.py
src/keri/app/cli/commands/query.py
src/keri/app/obtaining.py
src/keri/app/storing.py
src/keri/vc/handling.py
src/keri/vdr/verifying.py

Add credential apply endpoint to have an agent apply for a credential from another identifier.  Configure a default apply handler that will auto-issue any request for a GLEIF vLEI issuer credential.
Add static sink and path command line argument to enterprise agent.

Apply credential, auto-issue QVI and static sink for KIWI web app integration

---

src/keri/core/eventing.py
tests/core/test_witness.py

Closes #27 
Closes GLEIF-IT/vLEI#79 

Fix out of order escrow to preserve attached witness receipts.

---

src/keri/core/parsing.py
src/keri/vdr/viring.py
tests/app/test_signing.py

Just some code commenting catch up.

Complete doc strings and document signing tests.

---

.readthedocs.yaml
README.md
docs/conf.py
docs/index.rst
docs/requirements.txt
src/keri/vdr/eventing.py

* HTML Sphinx generated docs from docstrings
* First pass as a docs landing page
* Updated badges.

Publish docs to ReadTheDocs 

---

README.md
docs/index.rst

Getting codecov to display properly

Fix codecov badge

---

tests/app/test_httping.py
tests/app/test_kiwiing.py
tests/vdr/test_issuing.py

Fix build that should have worked.

---

scripts/demo/mbx.json
scripts/demo/multisig-agent.sh
src/keri/app/challenging.py
src/keri/app/cli/commands/agent/demo.py
src/keri/app/grouping.py
src/keri/app/indirecting.py
src/keri/app/kiwiing.py
src/keri/peer/exchanging.py
src/keri/vc/handling.py
tests/app/test_httping.py
tests/app/test_kiwiing.py
tests/vdr/test_issuing.py

* Refactor agent and witness cue and escrow processing
* Get all Agent notifications for delegation and multisig working. 

Agent mailbox

---

scripts/demo/anchor.json
scripts/demo/delegate-agent.sh
scripts/demo/mbx.json
scripts/demo/multisig-agent.sh
src/keri/app/agenting.py
src/keri/app/booting.py
src/keri/app/cli/commands/agent/demo.py
src/keri/app/cli/commands/delegate/confirm.py
src/keri/app/cli/commands/incept.py
src/keri/app/cli/commands/kevers.py
src/keri/app/cli/common/displaying.py
src/keri/app/delegating.py
src/keri/app/directing.py
src/keri/app/forwarding.py
src/keri/app/grouping.py
src/keri/app/habbing.py
src/keri/app/indirecting.py
src/keri/app/kiwiing.py
src/keri/core/parsing.py
src/keri/peer/exchanging.py
tests/app/test_agenting.py
tests/app/test_delegating.py
tests/app/test_grouping.py
tests/app/test_kiwiing.py

* Notifications for multisig incept, rotate and interact.
* Notifications for delegation incept, rotate and multisig delegate incept and rotate.
* Delegate query race condition fix.

Notifications for multisig incept, rotate and interact.

---

scripts/keri/cf/demo-witness-oobis-schema.json
scripts/keri/cf/demo-witness-oobis.json
src/keri/app/delegating.py
src/keri/app/indirecting.py
tests/config/keri/cf/main/wan.json
tests/config/keri/cf/main/wes.json
tests/config/keri/cf/main/wil.json

* Update default demo config file to not load schema.
* Add GET endpoint for mailbox SSE events.

Quick fixes

---

scripts/demo/delegate.sh
src/keri/app/cli/commands/contacts/list.py
src/keri/app/cli/commands/oobi/resolve.py
src/keri/app/cli/common/oobiing.py
src/keri/app/connecting.py
src/keri/app/indirecting.py
src/keri/app/kiwiing.py
src/keri/db/basing.py
src/keri/end/ending.py
tests/app/test_connecting.py
tests/app/test_kiwiing.py
tests/db/test_basing.py

* Local metadata (contact data) associated with identifiers
* Endpoints for CRUD of metadata.
* Endpoint for associating an image with an identifier.

Contact API for associating metadata and an image with identifiers.

---

src/keri/app/indirecting.py
src/keri/app/kiwiing.py
tests/app/test_kiwiing.py

* Adding ability to associate metadata with local identifiers.
* Added endpoint for retrieving key state and full KEL for any prefix in kevers.

Additional Agent Admin Endpoints.

---

scripts/demo/single-issuer-agent.sh
src/keri/app/challenging.py
src/keri/app/kiwiing.py
src/keri/app/storing.py

Update challenge endpoint to get notifications working.

---

src/keri/app/kiwiing.py
src/keri/core/scheming.py
tests/app/test_kiwiing.py

Schema loading is done thru DOOBIs (data OOBIs).  These endpoints are for admin access to already loaded schema.

Schema endpoints to allow controller of agent to get list of known schema.

---

src/keri/app/connecting.py
src/keri/app/kiwiing.py
src/keri/core/coring.py
src/keri/core/eventing.py
src/keri/db/basing.py
src/keri/end/ending.py
src/keri/peer/exchanging.py
src/keri/vdr/eventing.py
src/keri/vdr/verifying.py
tests/app/test_agenting.py
tests/app/test_connecting.py
tests/app/test_kiwiing.py
tests/db/test_basing.py

Sign contact data at rest and verify signatures at load.

---

scripts/demo/delegate-agent.sh
scripts/demo/multisig-agent.sh
src/keri/app/booting.py
src/keri/app/cli/commands/init.py
src/keri/app/cli/commands/oobi/resolve.py
src/keri/app/cli/commands/vc/issue.py
src/keri/app/cli/common/oobiing.py
src/keri/app/indirecting.py
src/keri/app/kiwiing.py
src/keri/db/basing.py
src/keri/end/ending.py
tests/app/test_kiwiing.py

Allow OOBI APIs to optionally create sign contact data with an alias

---

src/keri/app/connecting.py
tests/app/test_kiwiing.py

Add support for multi-valued queries for contact data.

---

scripts/demo/multisig-issuer-agent.sh
scripts/demo/multisig-issuer.sh
src/keri/app/agenting.py
src/keri/app/cli/commands/vc/registry/incept.py
src/keri/app/forwarding.py
src/keri/app/grouping.py
src/keri/app/indirecting.py
src/keri/app/kiwiing.py
src/keri/core/eventing.py
src/keri/vdr/credentialing.py
src/keri/vdr/eventing.py
tests/app/schema.json
tests/app/test_agenting.py
tests/app/test_issue_credential.py
tests/app/test_kiwiing.py
tests/core/test_witness.py

Test of full mutlsig credential issuance via agent APIs.

---

scripts/demo/mbx.json
src/keri/app/cli/commands/agent/demo.py
src/keri/app/forwarding.py
src/keri/app/grouping.py
src/keri/app/kiwiing.py
src/keri/app/storing.py
src/keri/app/watching.py
src/keri/core/cueing.py
tests/app/test_credentials.py
tests/app/test_grouping.py
tests/app/test_kiwiing.py
tests/app/test_multisig.py
tests/core/test_cueing.py

This PR includes mailbox notifications for:
* Multisig incept, rotate, interact
* Credential issue, revoke
* Multisig credential issue, revoke

Agent SSE mailbox notifications to the controller for:

---

src/keri/app/kiwiing.py
tests/app/test_kiwiing.py

Accept weighted thresholds through the multisig and identifier APIs

---

src/keri/app/kiwiing.py
tests/app/test_kiwiing.py

* Agent APIs for inspecting the contents of the KEL event  escrows.

Agent Escrow stat API

---

scripts/demo/multisig-issuer-agent.sh
scripts/demo/single-issuer-agent.sh
src/keri/app/kiwiing.py
tests/app/test_credentials.py

Multisig credential issuance scripts, front to back using 3 agents and curl commands.

---

tests/app/cli/commands/multisig/mtest-sample.json
tests/app/cli/commands/multisig/mtest/keri/cf/demo-witness-oobis.json
tests/app/cli/commands/multisig/mtest/keri/cf/main/wan.json
tests/app/cli/commands/multisig/mtest/keri/cf/main/wes.json
tests/app/cli/commands/multisig/mtest/keri/cf/main/wil.json
tests/app/cli/commands/multisig/test_multisig.py
tests/app/cli/test_kli_commands.py
tests/conftest.py

* Multisig command line tests.
* Adding coverage for status, sign and verify kli commands

Increasing code coverage for kli commands

---

scripts/demo/alice-bob-agent.sh
scripts/demo/demo-script.sh
scripts/demo/demo-witness-script.sh
scripts/demo/multisig-delegate-delegator.sh
scripts/demo/remote-witness-sample.json
scripts/demo/single-issuer.sh
scripts/keri/cf/remote-witness-oobis-schema.json
scripts/keri/cf/remote-witness-oobis.json
src/keri/app/agenting.py
src/keri/app/booting.py
src/keri/app/cli/commands/agent/demo.py
src/keri/app/cli/commands/kevers.py
src/keri/app/cli/commands/oobi/generate.py
src/keri/app/cli/commands/oobi/resolve.py
src/keri/app/cli/commands/status.py
src/keri/app/cli/commands/vc/list.py
src/keri/app/cli/commands/verify.py
src/keri/app/cli/commands/witness/start.py
src/keri/app/cli/common/oobiing.py
src/keri/app/cli/kli.py
src/keri/app/grouping.py
src/keri/app/habbing.py
src/keri/app/kiwiing.py
src/keri/core/eventing.py
src/keri/core/routing.py
src/keri/help/__init__.py
tests/app/test_agenting.py

* Minor updates to witnesses
* Headpathdir to boot for packaging
* Fixing long standing bug that added witnesses in a rotation were not returning receipts.  They new witness needed to be caught up or the events were ending up in out of order escrow.

Updates and fixed discovered during IIW prep

---

src/keri/app/cli/commands/witness/start.py
src/keri/app/cli/common/oobiing.py
src/keri/app/indirecting.py
src/keri/core/eventing.py
tests/app/test_agenting.py
tests/core/test_delegating.py
tests/core/test_escrow.py
tests/core/test_eventing.py
tests/core/test_expose.py

Supporting reentrant witnesses, removes a unicode character :( which was upsetting Keep downstream.

Feat reentrant

---

scripts/keri/cf/main/wil.json
src/keri/app/cli/commands/init.py
src/keri/app/cli/commands/witness/start.py
tests/app/cli/test_kli_commands.py

Make witnesses reentrant and identifiers use randy algo when no salt is provided.

---

scripts/demo/xbrl-data.json
scripts/keri/cf/main/wil.json
src/keri/app/cli/commands/vc/export.py

Fix witness config file accidentally broken
new xbrl data file.

Update to vc export for order of exported items.

---

src/keri/core/coring.py
tests/core/test_coring.py

Preparation to update code table for CESR native KERI messages.

removed unused provisional codes from counter code table

---

scripts/keri/cf/demo-witness-oobis-schema.json
src/keri/app/cli/commands/escrow.py
src/keri/app/cli/commands/vc/export.py
src/keri/end/ending.py
src/keri/vdr/verifying.py
tests/app/cli/test_kli_commands.py

* Fix VC export to export raw.
* New schema oobis in config sample.
* Fix verifying to accept a credential without an issuee.

Updates to support ACDC data attestations. 

---

.github/workflows/python-app-ci.yml

Update the GitHub CI branches to run on `main` and `development`

---

.readthedocs.yaml
src/keri/app/cli/commands/challenge/generate.py
src/keri/app/cli/commands/challenge/verify.py
src/keri/app/cli/commands/contacts/list.py
src/keri/app/cli/commands/incept.py
src/keri/app/cli/commands/init.py
src/keri/app/cli/commands/saidify.py
src/keri/app/cli/commands/vc/list.py
src/keri/app/cli/kli.py
src/keri/app/habbing.py
src/keri/app/storing.py
tests/app/cli/commands/challenge/alice.json
tests/app/cli/commands/challenge/bob.json
tests/app/cli/commands/challenge/keri/cf/demo-witness-oobis.json
tests/app/cli/commands/challenge/keri/cf/main/wan.json
tests/app/cli/commands/challenge/keri/cf/main/wes.json
tests/app/cli/commands/challenge/keri/cf/main/wil.json
tests/app/cli/commands/challenge/test_kli_challenge.py
tests/app/test_habbing.py
tests/conftest.py

Associated unit tests.
Updated contact list kli command
Some minor documentation clean up.

New kli commands `challenge generate` and `challenge verify` to participate in challenge respose from commandline. 

---

src/keri/app/booting.py
src/keri/app/cli/commands/agent/demo.py
src/keri/app/cli/commands/agent/start.py
src/keri/app/cli/commands/agent/vlei.py
src/keri/app/kiwiing.py
tests/app/test_specing.py

The lock and unlock now free all resources so there are no conflicts and the co-routine hierarchy is kept clean.

Fix lock / unlock to allow an agent to be successfully locked and unlocked

---

scripts/demo/credentials/multisig-holder-agent.sh

Created new script multisig-holder-agent.sh
The script includes the schema OOBis

Added multisig-holder-agent.sh in scripts/demo/credentials

---

scripts/demo/basic/multisig-delegate.sh
scripts/demo/basic/start-witness.sh
scripts/demo/credentials/multisig-issuer.sh
scripts/demo/credentials/single-issuer.sh
scripts/demo/data/wil-witness-sample.json
src/keri/app/cli/kli.py
tests/app/cli/commands/challenge/test_kli_challenge.py

Update a few more scripts with correct paths to files.

---

src/keri/app/cli/commands/agent/demo.py
src/keri/app/cli/commands/agent/start.py
src/keri/vdr/credentialing.py

Also updated two agent command lines to remove unneeded parameters.

Update to Tevery escrow processing to allow for successful processing of an event in the anchor-less escrow.

---

scripts/demo/vLEI/issue-xbrl-attestation-agent.sh
scripts/keri/cf/demo-witness-oobis-schema.json
src/keri/app/booting.py
src/keri/app/cli/commands/init.py
src/keri/app/cli/commands/oobi/resolve.py
src/keri/app/cli/kli.py
src/keri/app/delegating.py
src/keri/app/indirecting.py
src/keri/app/kiwiing.py
src/keri/app/oobiing.py
src/keri/db/basing.py
src/keri/end/ending.py
src/keri/vdr/credentialing.py
tests/app/test_delegating.py
tests/app/test_kiwiing.py
tests/db/test_basing.py
tests/end/test_ending.py

* Revamped OOBI processing to be more efficient and prevent database lock issues when running when the database is created from the Agent.  Now OOBI processing occurs in the background with staged escrow for retries.
* Added support for Blind/Self OOBIs.  All witnesses now expose their AID via the blind OOBI

Revamped OOBI processing and implemented Blind OOBIs

---

ref/getting_started.md

these changes make the code work
except places with comments:
`# this gets : AttributeError: ...`
`# this gets : TypeError: ..`

updated code in ref/getting_started.md

---

src/keri/app/cli/commands/vc/export.py
src/keri/core/parsing.py
src/keri/vdr/verifying.py

Minor fix to kli export and the verifier to support the vLEI reporting agent.

---

src/keri/app/delegating.py
src/keri/app/kiwiing.py
src/keri/app/oobiing.py
src/keri/db/dbing.py
tests/app/test_credentials.py
tests/app/test_delegating.py
tests/app/test_oobiing.py

Moved, fixed and tested OOBI sharing endpoint, EXN message and handler.

---

src/keri/app/kiwiing.py
tests/app/test_kiwiing.py

Minor updates for multisig create (metadata fix and supporting establishment only)

---

src/keri/app/habbing.py
src/keri/app/kiwiing.py

Adding support for "Do Not Delegate" to REST API and makeHab

---

src/keri/core/parsing.py

signatures as proem so can have two different indices for current and prior next key lists.
changes. Lines starting

added support for Prior_Next_Idx modifier code for indexed

---

src/keri/app/habbing.py
src/keri/app/keeping.py

fixed logic in keeping.Manager.sign to correctly interpret ondices

---

scripts/demo/data/external-gar-incept.json
scripts/demo/vLEI/external-gar-init.sh
src/keri/app/cli/commands/escrow.py
src/keri/app/grouping.py
src/keri/app/habbing.py
src/keri/app/kiwiing.py
src/keri/core/eventing.py
src/keri/db/basing.py
src/keri/end/ending.py
tests/app/test_grouping.py
tests/app/test_kiwiing.py
tests/core/test_eventing.py

- Additions to key state endpoint to include pre-kevery rotation events.
- New endpoint for finding an event by the public key.

Updates to support monitoring of distributed multisig rotation events

---

src/keri/app/cli/commands/vc/export.py
src/keri/app/kiwiing.py
src/keri/vc/proving.py
src/keri/vdr/credentialing.py
src/keri/vdr/verifying.py
src/keri/vdr/viring.py
tests/app/test_kiwiing.py
tests/vc/test_protocoling.py
tests/vc/test_proving.py
tests/vc/test_walleting.py
tests/vdr/test_txn_state.py

Allow for ACDC credentials with no edges (`e` field) in creation and verification.

---

scripts/demo/basic/demo-script.sh
src/keri/app/cli/commands/multisig/rotate.py
src/keri/end/ending.py

current sith (initial) isith and next sith (nsith).

More cleanup to support dual siths needed for new rotation logic. isith and nsith

---

scripts/keri/cf/vlei-root-oobis-schema.json

Remove well knowns from config file so issue script works.

---

scripts/keri/cf/demo-witness-oobis-schema.json

See also https://github.com/WebOfTrust/keripy/pull/332

Remove (more) well-knowns from demo config file so issue script works.

---

src/keri/app/grouping.py
src/keri/app/habbing.py
src/keri/app/kiwiing.py
src/keri/core/coring.py
src/keri/core/eventing.py
src/keri/vdr/eventing.py
tests/core/test_coring.py

added more round trip tests for tholder json

---

scripts/demo/basic/single-witness-create-agent.sh
scripts/keri/cf/demo-witness-oobis-schema.json
src/keri/app/indirecting.py

Enhance agent mailbox poller to have long poll feature to ensure connectivity even with sporadic connections.

---

src/keri/app/forwarding.py
src/keri/app/indirecting.py
src/keri/app/kiwiing.py
tests/app/test_credentials.py
tests/app/test_indirecting.py
tests/app/test_kiwiing.py
tests/app/test_multisig.py
tests/app/test_storing.py

Remove old use of Respondant from REST endpoint for signing and sending a challenge response.

---

src/keri/app/cli/commands/challenge/verify.py
src/keri/app/cli/commands/multisig/join.py
src/keri/app/forwarding.py
src/keri/app/indirecting.py

Updates for kli to work with new Hab changes, one minor fix in challenge verify and removing some prints

---

src/keri/app/cli/commands/delegate/confirm.py
src/keri/app/cli/commands/multisig/incept.py
src/keri/app/cli/commands/multisig/interact.py
src/keri/app/cli/commands/multisig/join.py
src/keri/app/grouping.py
src/keri/app/habbing.py
src/keri/app/kiwiing.py
src/keri/app/oobiing.py
src/keri/vdr/credentialing.py
tests/app/test_grouping.py

Missed a couple of places that were not recognizing rmids
Also some clean up

More refactor clean up to support smids and rmids

---

src/keri/app/oobiing.py
tests/app/test_oobiing.py

Allow for JSON Schema data OOBI to have content type "application/json".

---

scripts/demo/vLEI/issue-xbrl-attestation-agent.sh
scripts/keri/cf/vlei-gar-oobis-schema.json
scripts/keri/cf/vlei-lar-oobis-schema.json
scripts/keri/cf/vlei-qar-oobis-schema.json

- update iXBRL Data Attestation schema SAID in config files
- fix issue-xbrl-attestation-agent.sh script by removing empty source from issue qvi credential request
Signed-off-by: arshdeep singh <arsh.binny@gmail.com>

Fix ixbrl attestation agent script

---

src/keri/app/cli/commands/multisig/incept.py
src/keri/app/oobiing.py

Update multisig incept command for rmids

---

src/keri/app/cli/commands/multisig/continue.py
src/keri/app/cli/kli.py
src/keri/app/grouping.py

New kli multisig continue command that can pick up an incomplete multisig event and finish the processing.

---

src/keri/app/cli/commands/did/generate.py

Added `kli did generate` command line command.

---

src/keri/app/cli/commands/did/generate.py
src/keri/app/cli/commands/list.py
src/keri/app/cli/commands/vc/issue.py

- vc issue now supports an option for naming the file to write the credential to
- removed unnecessary try/except from cv list
- fixed did generate to use full witness OOBI.

Minor updates to kli commands:

---

scripts/demo/basic/multisig-delegate-delegator.sh
scripts/demo/test_scripts.sh
src/keri/app/cli/commands/delegate/confirm.py
tests/end/test_ending.py

Also:
- Updated the mutlsig-delegate-delegator.sh script to use the kli delegate confirm instead of interact.
- Added multisig-delegate-delegator.sh to test_scripts to be run on every PR.

Fix the kli delegate confirm command to work with multisig delegator AIDs (interaction events only).

---

setup.py
src/keri/__init__.py
src/keri/app/cli/commands/did/generate.py
src/keri/app/cli/commands/init.py
src/keri/app/cli/commands/multisig/shell.py
src/keri/app/httping.py
src/keri/app/oobiing.py
src/keri/db/basing.py
tests/core/test_coring.py

Changes to support OOBI resolution of vLEI GLEIF RoOT AID.

Update DID kli commands to generate new formats

---

tests/app/test_grouping.py

Created a new test involving a 7 member group AID rotating 2 times with one set of 3 members then rotating again with a disjoint set of 3 members to ensure a recovery rotation will work correctly.

New test for partial rotation

---

src/keri/app/agenting.py

Updating witnessing logic of controller to share KEL of delegator with witnesses if AID is a delegated AID.

---

src/keri/app/cli/commands/contacts/list.py
src/keri/app/cli/commands/delegate/request.py
src/keri/app/kiwiing.py

New utility to resend delegation requests from a delegated AID to the delegator.

---

src/keri/end/ending.py
tests/end/test_ending.py

Make static sink optional in ending module and leave it turned off for witnesses.

---

src/keri/app/agenting.py
src/keri/db/basing.py
src/keri/vdr/credentialing.py

Make delegation receipting recursive to account for nested chained delegation.

---

src/keri/app/habbing.py

Apply recursive delegation logic to OOBI resolution.

---

src/keri/app/cli/common/displaying.py
src/keri/app/grouping.py

Fix witnessing election logic of Counselor to correctly select the participant (signer) with the lowest index.

Fix witnessing election logic of Counselor

---

src/keri/app/cli/commands/vc/present.py

Missed one reference to the sender hab's prefix.

---

src/keri/app/cli/commands/vc/list.py
src/keri/app/cli/commands/vc/registry/incept.py
src/keri/app/cli/commands/vc/registry/status.py
src/keri/vdr/credentialing.py
src/keri/vdr/eventing.py
src/keri/vdr/viring.py
tests/vdr/test_verifying.py

Some minor spelling fixes that I noticed while using the kli.

spelling fixes (credential, registry)

---

src/keri/app/cli/commands/delegate/confirm.py
src/keri/app/cli/commands/rotate.py
src/keri/app/configing.py
src/keri/app/directing.py
src/keri/app/forwarding.py
src/keri/app/habbing.py
src/keri/app/indirecting.py
src/keri/app/keeping.py
src/keri/core/coring.py
src/keri/core/eventing.py
src/keri/core/scheming.py
src/keri/db/basing.py
src/keri/db/dbing.py

Some small typos and word corrections I found.

docs: correct comment spelling and content

---

src/keri/app/cli/kli.py
src/keri/app/grouping.py
src/keri/app/habbing.py
src/keri/core/coring.py
src/keri/core/eventing.py
src/keri/db/basing.py
src/keri/kering.py
src/keri/vdr/credentialing.py
tests/app/test_grouping.py
tests/app/test_kiwiing.py
tests/core/test_coring.py
tests/core/test_eventing.py
tests/core/test_partial_rotation.py
tests/db/test_basing.py

Implementation of KEL walking to resolve rotation participation of members with signing authority and rotation authority in group multisig AIDs.

KEL Walking for Rotation

---

scripts/demo/basic/demo-witness-script.sh
scripts/demo/basic/multisig-partial-rotation.sh
src/keri/app/cli/commands/local/watch.py
src/keri/app/cli/commands/oobi/resolve.py
src/keri/app/cli/commands/status.py
src/keri/app/habbing.py
tests/core/test_coring.py

Bug fixes for the new kli local watch command to avoid hanging on a bad witness
Bug fix for the Habery to accept aliases with "." in the name.
New parameter to kli oobi resolve to force re-resolution of an already resolved oobi

Several kli updates, one Habery fix

---

src/keri/app/cli/commands/list.py
src/keri/app/cli/commands/oobi/clean.py

Helper kli utility to delete OOBIs stuck in resolution

---

src/keri/app/cli/commands/witness/start.py

This aligns `kli witness start` with `kli agent start` for the `--config-dir` and `--config-file` args.
While this is functional there is one problem. There are empty config files written to `$CONFIG_DIR/keri/cf` while the files in `$CONFIG_DIR/keri/cf/main` are the ones that must be populated. This is annoying and I would rather eliminate this behavior before this is merged.

feat: config witnesses by file and dir args

---

src/keri/core/coring.py
src/keri/core/eventing.py
src/keri/core/parsing.py
src/keri/core/scheming.py
src/keri/vc/proving.py
tests/app/test_credentials.py
tests/app/test_signing.py
tests/conftest.py
tests/core/test_coring.py
tests/core/test_scheming.py
tests/db/test_escrowing.py
tests/vc/test_protocoling.py
tests/vc/test_proving.py
tests/vdr/test_verifying.py

Make said field label designation differntiated better from protocol type designation
Start on Sadder.

Refactoring to prepare for ensuring consistent said verification of all keri events

---

.github/workflows/python-app-ci.yml
src/keri/app/querying.py
src/keri/end/ending.py
tests/app/test_querying.py

* A rewrite of the Query Doer used in the kli query command to be more hio-ic
* Fix OOBIEnd to not reply to an OOBI request for an AID that doesn't have a threshold satisfying number of witness receipts.

Query rewrite and bug fix

---

src/keri/core/coring.py

added parameter to function sizeify, version parameter so can specify required supported version instead of hard coded

start refactor of Sadder so it can self-verify ans self-saidify

---

src/keri/app/habbing.py

Minor update to SignifyHab to properly handle delegated AIDs

Fix SignifyHab to work with delegated AIDs.

---

src/keri/core/coring.py
src/keri/end/ending.py
src/keri/kering.py
src/keri/vc/proving.py
tests/core/test_coring.py

continued work on new Serdery and Serder in test code

Add genera for ACDC to ProDex

---

src/keri/app/agenting.py
src/keri/app/delegating.py
src/keri/app/forwarding.py
src/keri/app/habbing.py
src/keri/app/querying.py

This PR fixes one issue with not streaming delegator KEL during an introduction

Updates to ensure "introducing" a delegated AID works correctly.

---

scripts/demo/basic/multisig-signify-rotation.sh
scripts/demo/data/multisig-signify-sample.json
src/keri/app/forwarding.py
src/keri/app/httping.py
src/keri/core/eventing.py

* script updates to test multisig interactions with Signify and KERI
* A small fix to HTTP CESR Streaming to support directly streaming ACDC credentials.

Update for testing Signify multisig and credentials

---

src/keri/app/challenging.py
src/keri/app/cli/commands/did/generate.py
src/keri/app/cli/commands/oobi/generate.py
src/keri/app/cli/commands/vc/registry/list.py
src/keri/app/cli/common/existing.py
src/keri/app/connecting.py
src/keri/app/keeping.py
src/keri/app/kiwiing.py
src/keri/app/oobiing.py
src/keri/app/signing.py
src/keri/core/coring.py
src/keri/core/serdering.py
src/keri/db/basing.py
src/keri/vdr/viring.py
tests/app/test_signing.py
tests/core/test_delegating.py

This fixes various docs typos and adds or corrects documentation I found is missing.

Fix typos, add missing docs

---

scripts/demo/credentials/multisig-issuer.sh
src/keri/app/cli/commands/vc/revoke.py
src/keri/vdr/eventing.py

Adds the date time stamp as an option that must be shared between revocation participants.

Update the kli revoke command to support multisig revocation

---

scripts/demo/basic/multisig-rotation-join.sh
src/keri/app/cli/commands/delegate/confirm.py
src/keri/app/cli/commands/multisig/interact.py
src/keri/app/cli/commands/multisig/join.py
src/keri/app/cli/commands/multisig/rotate.py
src/keri/app/cli/kli.py
src/keri/app/grouping.py
src/keri/app/kiwiing.py
tests/app/test_grouping.py
tests/app/test_kiwiing.py

* Adding support for joining a multisig group with a rotation that adds my AID as a participant from the kli.

Add ability to join new multisig group from command line

---

src/keri/app/httping.py

Added the possibility send body and headers to allow for POST and PUT http methods

Support for POST and PUT method in the Clienter

---

src/keri/app/delegating.py
src/keri/app/grouping.py

This PR includes fixes to the Counselor and Boatswain to allow for communication of events from a delegated multisig AID in KERIA.

Add a proxy to Boatswain and a Boatswain to Counselor.

---

src/keri/app/cli/commands/multisig/notice.py

This PR adds a new kli command for re-sending the required EXN messages after a multisig rotation.

Multisig notice command for resending notifications of a rotation to other pariticpants.

---

src/keri/app/cli/commands/agent/vlei.py

Fixed spelling of scenario in keri agent vlei log message

---

src/keri/vc/protocoling.py

This error was causing a crash KERIA.

Super small fix in presentation request

---

scripts/demo/basic/multisig.sh
src/keri/app/cli/commands/did/generate.py
src/keri/app/cli/commands/ends/add.py
src/keri/app/cli/commands/ends/export.py
src/keri/app/cli/commands/ends/list.py
src/keri/app/cli/commands/multisig/ends/add.py
src/keri/app/cli/commands/multisig/interact.py
src/keri/app/cli/commands/multisig/join.py
src/keri/app/grouping.py
src/keri/app/habbing.py
src/keri/core/eventing.py
src/keri/core/routing.py

The PR includes:
* Fix to properly reload SignifyGroupHabs on restart
* New kli command for adding endpoint role authorizations for single signature AIDs
* New kli command for adding endpoint role authorizations for group multisig AIDs

Updates in support of group multisig endpoints for Agents

---

src/keri/app/cli/commands/multisig/ends/add.py
src/keri/core/eventing.py

New command line tool which negotiates with other members of the multisig to generate end role authorizations for the multisig for each of the endpoint auth records of the menbers.

Final version of endpoint role authorization command line tool for multisig AIDs.

---

scripts/demo/credentials/single-issuer.sh
src/keri/app/kiwiing.py
src/keri/app/notifying.py
tests/app/test_credentials.py
tests/app/test_delegating.py
tests/app/test_multisig.py
tests/app/test_notifying.py

This PR includeS:
* New support for index based pagination for notifications.

Support for start and end indexes and counts for Notifications.

---

src/keri/core/coring.py
src/keri/core/parsing.py
src/keri/db/basing.py
src/keri/peer/exchanging.py
src/keri/vc/protocoling.py
tests/core/test_coring.py
tests/vc/test_protocoling.py

* Fix for apply IPEX message
* Fix for Pather resolution for handling bad keys

Fixes for exchange messages

---

src/keri/app/forwarding.py

* Update to message forwarding to honor all non-witness end roles

Update to message forwarding to honor all non-witness end roles

---

src/keri/app/cli/commands/ipex/admit.py
src/keri/app/cli/commands/ipex/grant.py

This PR includes a fix for the grant command and closes #583

Fix to grant command for broken single sig granting.

---

src/keri/app/cli/commands/incept.py
src/keri/app/cli/common/incepting.py
tests/app/cli/test_kli_commands.py

This PR includes a fix for the transferable argument in incept.

Update incept args to get the transferable argument to work correctly.

---

scripts/demo/credentials/multisig-signify-issue.sh
src/keri/core/parsing.py
tests/core/test_coring.py

* Fix multisig script to track PIDs correctly.
* Remove a few unneeded prints.

Minor clean-up

---

src/keri/app/habbing.py
src/keri/app/keeping.py

This PR includes a fix to support for random key generation.

Updating to Hab and Manager to properly support random key generation

---

src/keri/app/agenting.py
src/keri/app/cli/commands/ipex/grant.py
src/keri/app/cli/commands/ipex/list.py
src/keri/vdr/viring.py

* Update to grant to send chained credentials when needed.

Update to grant to send chained credentials when needed.

---

src/keri/app/cli/commands/vc/list.py
src/keri/vdr/viring.py

This PR is a small change to load schema JSON into credential results.

Update to load schema JSON into credential results.

---

src/keri/app/agenting.py

* Update to the telquery feature to properly query when issuers only have Agents and not witnesses.

Telquery fix

---

src/keri/core/eventing.py
src/keri/db/basing.py

Also some refactor and cleanup.
Uses db.pubs to find public keys.

Added logic to strip local signatures on group KEL events when event sourced remotely (nonlocal not protected)

---

src/keri/app/agenting.py
src/keri/vdr/verifying.py

This PR fixes 2 edge cases where exceptions needed to be caught and accounted for instead of bubbling out of Doers.

Fix 2 exception cases that were incorrectly letting exceptions leak out of Doers and causing crashes.

---

scripts/demo/test_scripts.sh

Fixed printf statement in test_scripts.sh

Fixed printf statement in test_scripts.sh

---

.github/workflows/python-app-ci.yml
.readthedocs.yaml
README.md
setup.py

This PR pushes us to latest Python version at 3.12.1

Update to Python 3.12.1

---

Makefile
setup.py
src/keri/__init__.py
src/keri/vdr/viring.py
tests/vdr/test_verifying.py

This PR pulls in a fix to cloneCreds that has already been merged into development

Hot fixing cloneCreds fix into main.

---

src/keri/app/cli/commands/migrate.py

This PR updates the migrate command to fix registry state entries in the database.

Hotfix 1.1.5

---

scripts/demo/credentials/multisig-issuer.sh
scripts/demo/credentials/oobi-new_multisig_issuer.sh
scripts/demo/credentials/rotate-multisig-issuer.sh
src/keri/app/cli/commands/migrate.py
src/keri/app/cli/commands/vc/export.py
src/keri/app/habbing.py
src/keri/vdr/credentialing.py

- Fix to saving SignifyGroupHabs to enable reloading
- Fix to credential export to support exporting all credentials.

Includes 2 fixes

---

scripts/demo/basic/migrate-quadlet.sh
scripts/demo/basic/rotate-new-quartet.sh
scripts/demo/credentials/multisig-grant-multisig-admit.sh
scripts/demo/credentials/multisig-issuer-interactive.sh
scripts/demo/credentials/multisig-issuer.sh
scripts/demo/data/issuee-1-sample.json
scripts/demo/data/issuee-2-sample.json
scripts/demo/data/issuee-multisig-sample.json
scripts/demo/data/issuer-1-sample.json
scripts/demo/data/issuer-2-sample.json
scripts/demo/data/issuer-multisig-sample.json
src/keri/app/cli/commands/ipex/admit.py
src/keri/app/cli/commands/ipex/grant.py
src/keri/app/cli/commands/ipex/join.py
src/keri/app/cli/commands/multisig/join.py
src/keri/app/cli/commands/time.py
src/keri/vc/protocoling.py

* fix to `kli multisig join` to work with IPEX ADMIT
* Script to demonstrate join working across GRANT and ADMIT for multisig.

Update to kli multisig join command work correctly for IPEX ADMIT messages

---

src/keri/app/cli/commands/vc/revoke.py

This functionality got clobbered in a merge.

Add support for the --send argument back into `kli revoke`. 

---

.github/workflows/python-app-ci.yml
src/keri/app/cli/commands/contacts/list.py
src/keri/app/cli/commands/multisig/update.py

* Update to contact list to account for non-backward compatible changes
* Updates multisig update to account for KeyStateRecord changes.
* Remove development branch from CI

Update to contact list to account for non-backward compatible changes

---

src/keri/core/serdering.py
tests/core/test_serdering.py

Added support for Serder.makify and .verify for CESR native keri

---

.github/workflows/python-app-ci.yml

This PR is an attempt to install libsodium for Macos only as a short term workaround

Attempt to conditionally run `brew install libsodium` on macos-latest build

---

src/keri/app/cli/commands/ipex/agree.py
src/keri/app/cli/commands/ipex/apply.py
src/keri/app/cli/commands/ipex/offer.py
src/keri/app/cli/commands/nonce.py
src/keri/core/coring.py
src/keri/vdr/eventing.py
tests/app/test_connecting.py
tests/app/test_grouping.py
tests/app/test_signing.py
tests/conftest.py
tests/vc/test_protocoling.py
tests/vc/test_walleting.py
tests/vdr/test_eventing.py
tests/vdr/test_txn_state.py
tests/vdr/test_verifying.py

PR of [issue#739](https://github.com/WebOfTrust/keripy/issues/739)

Deprecate randomNonce() and refactor using Salter().qb64

---

scripts/demo/basic/multisig-rotate-three-stooges.sh
scripts/demo/data/multisig-three-aids.json
scripts/demo/test_scripts.sh

The cool names distracted me from changing the AID Prefixes. This PR fixes that and adds the stooges to the integration test suite.

fix: stooge AID Prefixes and run in test_scripts.sh

---

scripts/demo/basic/delegate.sh
scripts/demo/test_scripts.sh
src/keri/app/cli/commands/delegate/confirm.py
src/keri/app/cli/commands/incept.py
src/keri/app/cli/commands/rotate.py
src/keri/app/delegating.py
src/keri/core/eventing.py
src/keri/core/parsing.py
src/keri/db/basing.py

This PR reversed the order of witness receipting and delegation approval request and updated command line tools to work correctly.  Re-enabled the delegate.sh script in CI/CD.

Updates to delegation processing to fix delegation.

---

src/keri/app/cli/commands/delegate/request.py
src/keri/app/cli/commands/ipex/grant.py
src/keri/app/cli/commands/multisig/notice.py
src/keri/app/cli/commands/vc/create.py
src/keri/app/cli/commands/vc/registry/incept.py
src/keri/app/grouping.py
src/keri/app/habbing.py
src/keri/app/notifying.py
src/keri/vdr/credentialing.py

Add more clean up than the 1.1.14 version.

cleans up some usage of coring.serder

---

src/keri/app/cli/commands/escrow.py
src/keri/app/cli/commands/kevers.py

Not sure if this text is 100% but wanted this PR to spur direction from someone who did have a better idea of what should go here.  Previous help text was incorrect.

Adjusted help text for escrow/kevers to better match their intended functionality

---

src/keri/app/httping.py
src/keri/core/eventing.py
src/keri/db/basing.py
tests/app/test_querying.py

Updated usages and removed db specific methods. Added test_query_not_found_escrow to test_querying.py

Replaced qnfs db with subing.IoSetSuber

---

src/keri/app/cli/commands/escrow/__init__.py
src/keri/app/cli/commands/escrow/clear.py
src/keri/app/cli/commands/escrow/list.py
src/keri/db/basing.py
tests/app/cli/test_kli_commands.py
tests/db/test_basing.py

We have it in main and 1.1.30, just sharing the love

adds escrow clear

---

src/keri/core/routing.py

Added missing `%s` to logging statement.

Logging Fix

---

src/keri/core/counting.py
tests/core/test_counting.py

As per the discussion today
@kentbull @m00sey @pfeairheller

Added Generic Groups to Counter Codes v1 CESR for forward compat with v2 CESR

---

src/keri/app/cli/commands/export.py

Fixes export with ends, previously just errored out.

fix export

---

src/keri/app/agenting.py
src/keri/app/apping.py
src/keri/app/cli/commands/incept.py
src/keri/app/cli/commands/init.py
src/keri/app/cli/commands/multisig/incept.py
src/keri/app/cli/commands/rotate.py
src/keri/app/configing.py
src/keri/app/delegating.py
src/keri/app/forwarding.py
src/keri/app/grouping.py
src/keri/app/habbing.py
src/keri/app/httping.py
src/keri/app/indirecting.py
src/keri/app/keeping.py
src/keri/app/oobiing.py
src/keri/app/signaling.py
src/keri/app/storing.py
src/keri/db/basing.py
src/keri/vc/walleting.py
src/keri/vdr/credentialing.py
tests/app/test_agenting.py

ported from Sam's commit to main in PR #945

Update Doer method signatures to support new Hio multiprocessing safety

---

scripts/demo/test_scripts.sh

enable multisig delegation script

---

src/keri/app/indirecting.py
tests/app/test_agenting.py

Replaced doist.do with explicit while loops that call doist.recur and check for break conditions.  Seems much faster on my machine, but we'll see.

Remove doist.do call from witness inquisitor, that doesn't seem to work for this test.
